
CREATE PROCEDURE "SAP_TM_TRP"."P_QUERY_ZONE_LOC"(IN ZONE_NAME NVARCHAR(20),OUT LOC_TAB TABLE(ID NVARCHAR(22))) AS
BEGIN

DECLARE ZONE_ID NVARCHAR(22);

SELECT SCUGUID22 INTO ZONE_ID FROM "SAPTMW"."/SCMB/TOENTITY" WHERE ENTITY = :ZONE_NAME AND MANDT = '800';
ZONEID_LV1 = SELECT DISTINCT A.CNODEID AS ZONEID,B.ENTITY AS ZONE_NAME FROM "SAPTMW"."Z_ZONE_HRC" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.CNODEID = B.SCUGUID22
WHERE A.PNODEID = :ZONE_ID AND B.MANDT = '800';
LOC_LV1 = SELECT A.LOCNO AS LOCNO,B.SCUGUID22 AS ID FROM "SAPTMW"."Z_ZONE_D" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.LOCNO = B.ENTITY
WHERE A.ID_ZONE IN (SELECT DISTINCT ZONE_NAME FROM :ZONEID_LV1) AND A.LOCNO IN (SELECT LOCNO FROM "SAPTMW"."Z_BKLOC")
AND B.MANDT = '800'
AND B.SCUGUID IN (SELECT DISTINCT LOCATION_UUID FROM "SAPTMW"."/TRP/RES_SHTRK" WHERE MOVEMENT_STATUS = 'NIT');


ZONEID_LV2 = SELECT DISTINCT A.CNODEID AS ZONEID,B.ENTITY AS ZONE_NAME FROM "SAPTMW"."Z_ZONE_HRC" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.CNODEID = B.SCUGUID22
WHERE A.PNODEID IN (SELECT DISTINCT ZONEID FROM :ZONEID_LV1) AND B.MANDT = '800';
LOC_LV2 = SELECT A.LOCNO AS LOCNO,B.SCUGUID22 AS ID FROM "SAPTMW"."Z_ZONE_D" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.LOCNO = B.ENTITY
WHERE A.ID_ZONE IN (SELECT DISTINCT ZONE_NAME FROM :ZONEID_LV2) AND A.LOCNO IN (SELECT LOCNO FROM "SAPTMW"."Z_BKLOC")
AND B.MANDT = '800'
AND B.SCUGUID IN (SELECT DISTINCT LOCATION_UUID FROM "SAPTMW"."/TRP/RES_SHTRK" WHERE MOVEMENT_STATUS = 'NIT');



ZONEID_LV3 = SELECT DISTINCT A.CNODEID AS ZONEID,B.ENTITY AS ZONE_NAME FROM "SAPTMW"."Z_ZONE_HRC" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.CNODEID = B.SCUGUID22
WHERE A.PNODEID IN (SELECT DISTINCT ZONEID FROM :ZONEID_LV2) AND B.MANDT = '800';
LOC_LV3 = SELECT A.LOCNO AS LOCNO,B.SCUGUID22 AS ID FROM "SAPTMW"."Z_ZONE_D" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.LOCNO = B.ENTITY
WHERE A.ID_ZONE IN (SELECT DISTINCT ZONE_NAME FROM :ZONEID_LV3) AND A.LOCNO IN (SELECT LOCNO FROM "SAPTMW"."Z_BKLOC")
AND B.MANDT = '800'
AND B.SCUGUID IN (SELECT DISTINCT LOCATION_UUID FROM "SAPTMW"."/TRP/RES_SHTRK" WHERE MOVEMENT_STATUS = 'NIT');

LOC_TAB =
SELECT DISTINCT ID FROM (
SELECT ID FROM :LOC_LV1 WHERE LOCNO LIKE 'FR%' OR LOCNO LIKE 'US%'
UNION
SELECT ID FROM :LOC_LV2 WHERE LOCNO LIKE 'FR%' OR LOCNO LIKE 'US%'
UNION
SELECT ID FROM :LOC_LV3 WHERE LOCNO LIKE 'FR%' OR LOCNO LIKE 'US%'
);


END;



DROP PROCEDURE "SAP_TM_TRP"."P_CREATE_TRP_SAMPLE_DATA";
CREATE PROCEDURE "SAP_TM_TRP"."P_CREATE_TRP_SAMPLE_DATA" ()
AS

BEGIN
---global variables definitions
DECLARE HOT_LOC_FILTER_ID BIGINT;
DECLARE FR_LOC_FILTER_ID BIGINT;
DECLARE FR_SP_FILTER_ID BIGINT;
DECLARE US_SP_FILTER_ID BIGINT;
DECLARE RES_FILTER_ID BIGINT;
DECLARE SCHED_LOC_FILTER_ID BIGINT;
DECLARE REG_FR_FILTER_ID BIGINT;
DECLARE HOT_REG_FILTER_ID BIGINT;
DECLARE TIME_FILTER_ID BIGINT; 
DECLARE COST_MODEL_ID BIGINT;
DECLARE SD_STOCK_ALERT_RULE_ID BIGINT;
DECLARE SD_FCST_ALERT_RULE_ID BIGINT;
DECLARE IDLE_RATE_ALERT_RULE_ID BIGINT;
DECLARE PICKUP_LDR_ID BIGINT;
DECLARE RETURN_LDR_ID BIGINT;
DECLARE RES_STK_ALERT_RULE_ID BIGINT;
DECLARE RES_STK_BUB_ALERT_RULE_ID BIGINT;
DECLARE SD_KPI_BUB_ALERT_RULE_ID BIGINT;
DECLARE AVC_PLAN_ALERT_RULE_ID BIGINT;
DECLARE AVC_LVL_ALERT_RULE_ID BIGINT;
--DECLARE QTT_ALERT_RULE_ID BIGINT;
DECLARE SD_PIPELINE_MODEL_ID BIGINT;
DECLARE KPI_IMP_EXP_PIPELINE_MODEL_ID BIGINT;
DECLARE KPI_PIPELINE_MODEL_ID BIGINT;
DECLARE SD_ALERT_RULE_GROUP_ID BIGINT;
DECLARE KPI_ALERT_RULE_GROUP_ID BIGINT;


----------------------------------------CREATE TRANSPORTATION ACTIVITIES AND EVENT CODE
/*
BEGIN



INSERT INTO "SAPTMW"."/SCMTMS/C_TRAC" SELECT * FROM "I075181"."/SCMTMS/C_TRAC" WHERE MANDT = '800' AND TRANSP_ACTIVITY NOT IN (
'01','02','03','04','05','06','07','08','09','10','99'
);

INSERT INTO "SAPTMW"."/SCMTMS/C_TRACT" SELECT * FROM "I075181"."/SCMTMS/C_TRACT" WHERE MANDT = '800' AND LANGU = 'E' AND TRANSP_ACTIVITY NOT IN (
'01','02','03','04','05','06','07','08','09','10','99'
);


INSERT INTO "SAPTMW"."/SCMTMS/C_EV_TY" SELECT * FROM "I075181"."/SCMTMS/C_EV_TY" WHERE MANDT = '800' AND STOP_CAT = 'S' AND TRANSP_ACTIVITY NOT IN (
'01','02','03','04','05','06','07','08','09','10','99'
);

INSERT INTO "SAPTMW"."/SCMTMS/C_EV_TYT" 
SELECT * FROM "I075181"."/SCMTMS/C_EV_TYT" 
WHERE MANDT = '800' AND LANGU = 'E'
AND TOR_EVENT IN (SELECT DISTINCT TOR_EVENT FROM "I075181"."/SCMTMS/C_EV_TY" WHERE MANDT = '800' AND STOP_CAT = 'S' AND TRANSP_ACTIVITY NOT IN (
'01','02','03','04','05','06','07','08','09','10','99'));

INSERT INTO "SAPTMW"."/TRP/RES_TRKMAP" SELECT * FROM "I075181"."/TRP/RES_TRKMAP" WHERE FIELD_VALUE != '' AND MAPPING_VALUE != '';

END;
*/

--------------------create role FR_DM3,FR_RP3 and assignment
BEGIN

DECLARE ROLE_GROUP_ID INTEGER;
DECLARE NAME NVARCHAR(50);
DECLARE DESC NVARCHAR(50);
DECLARE ROLE_ID BIGINT;
DECLARE USER_ID BIGINT;
DECLARE RP_USER_NAME NVARCHAR(60) DEFAULT 'TRPPLAN';
DECLARE DM_USER_NAME NVARCHAR(60) DEFAULT 'TRPDEP';
--create depot manager role
ROLE_GROUP_ID := 1;
NAME := 'FR_DM';
DESC := 'Franch Depot Manager';

CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_role_create"(:ROLE_GROUP_ID,:NAME,:DESC,:ROLE_ID);
LOCIDS = SELECT DISTINCT A.LOCID AS ID FROM "SAPTMW"."/SAPAPO/LOC" AS A INNER JOIN "SAPTMW"."Z_BKLOC" AS B
ON A.LOCNO = B.LOCNO WHERE A.MANDT = '800' AND B.LOCNO LIKE 'FR%';
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_role_location_create" (:ROLE_ID,:LOCIDS);
--assign role FR_DM1 to user TRPDEP
ROLES = SELECT DISTINCT ID FROM "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_role"
        WHERE NAME = :NAME;
SELECT ID INTO USER_ID FROM "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user"
        WHERE USERNAME = :DM_USER_NAME;
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_ext_assign_role"(
        :USER_ID,1,:ROLES); 


--create regional planner role
ROLE_GROUP_ID := 3;
NAME := 'FR_RP';
DESC := 'Franch Regional Planner';
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_role_create"(:ROLE_GROUP_ID,:NAME,:DESC,:ROLE_ID);
RGS = SELECT LOCID AS ID FROM "SAPTMW"."/SAPAPO/LOC" WHERE LOCNO IN ('115','21','230');
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_role_region_create" (:ROLE_ID,:RGS);
--assign role FR_RP1 to user TRPPLAN 
ROLES = SELECT DISTINCT ID FROM "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_role"
        WHERE NAME = :NAME;
SELECT ID INTO USER_ID FROM "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user"
        WHERE USERNAME = :RP_USER_NAME;
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_ext_assign_role"(
        :USER_ID,3,:ROLES); 


--create super regional planner role
ROLE_GROUP_ID := 3;
NAME := 'ALL_RP';
DESC := 'Franch Regional Planner';
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_role_create"(:ROLE_GROUP_ID,:NAME,:DESC,:ROLE_ID);
RGS = SELECT LOCID AS ID FROM "SAPTMW"."/SAPAPO/LOC" WHERE LOCNO = 'ADMI';
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_role_region_create" (:ROLE_ID,:RGS);
--assign role FR_RP1 to user TRPPLAN 
ROLES = SELECT DISTINCT ID FROM "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_role"
        WHERE NAME = :NAME;
SELECT ID INTO USER_ID FROM "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user"
        WHERE USERNAME = :RP_USER_NAME;
CALL "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::p_ext_assign_role"(
        :USER_ID,3,:ROLES); 


END;




-----------------create location filter ----------------------------------
BEGIN 

DECLARE NAME VARCHAR(50);
DECLARE DESC VARCHAR(500);
DECLARE VISIBLE_FLAG VARCHAR(3);
DECLARE ITEMS TABLE (ID NVARCHAR(22));
DECLARE LOCATION_TYPE INT;

--assign values to input parameters
NAME := 'FR_LOCS';
DESC := 'Hot Locations in Franch';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
ITEMS = SELECT DISTINCT A.LOCID AS ID FROM "SAPTMW"."/SAPAPO/LOC" AS A INNER JOIN "SAPTMW"."Z_BKLOC" AS B
ON A.LOCNO = B.LOCNO WHERE A.MANDT = '800' AND B.LOCNO LIKE 'FR%';

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :FR_LOC_FILTER_ID);


NAME := 'FR_SP';
DESC := 'Specific Locations of Franch for TRP Demo';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
--GET LOCATION IDS
CALL "SAP_TM_TRP"."P_QUERY_ZONE_LOC"('115',ITEMS);

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :FR_SP_FILTER_ID);

NAME := 'US_SP';
DESC := 'Specific Locations of USA for TRP Demo';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
--GET LOCATION IDS
CALL "SAP_TM_TRP"."P_QUERY_ZONE_LOC"('230',ITEMS);

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :US_SP_FILTER_ID);


--assign values to input parameters
NAME := 'HOT_LOCS';
DESC := 'Hot Locations in Booking';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
ITEMS = SELECT DISTINCT A.LOCID AS ID FROM "SAPTMW"."/SAPAPO/LOC" AS A INNER JOIN "SAPTMW"."Z_BKLOC" AS B ON A.LOCNO = B.LOCNO WHERE A.MANDT = '800';
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :HOT_LOC_FILTER_ID);



---create region type location filter
NAME := 'REG_FR';
DESC := 'Part Regions Included for Demo';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 5;
ITEMS = SELECT LOCID AS ID FROM "SAPTMW"."/SAPAPO/LOC" WHERE LOCNO IN ('115','21','230');
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :REG_FR_FILTER_ID);

---create region type SUPER location filter
NAME := 'HOT_REG';
DESC := 'Part Regions Included for Demo';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 5;
ITEMS = SELECT LOCID AS ID FROM "SAPTMW"."/SAPAPO/LOC" WHERE LOCNO = 'ADMI';
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :HOT_REG_FILTER_ID);




END;


-------------------create resource filter MURES----------------------------------
BEGIN

DECLARE NAME VARCHAR(50);
DECLARE DESC VARCHAR(500);
DECLARE VISIBLE_FLAG VARCHAR(3);
DECLARE ITEMS TABLE (ID NVARCHAR(22));
DECLARE FILTER_TYPE INT;
--assign valuess to input parameters
NAME := 'MURES';
DESC := 'Most Used resources';
FILTER_TYPE := 1;
VISIBLE_FLAG := 'G';

ITEMS = SELECT DISTINCT T1.EQUI_CODE AS ID FROM "SAPTMW"."/SCMB/EQUI_CODE" T1 INNER JOIN "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement::v_client_code" CC 
ON T1.MANDT = CC.MANDT WHERE T1.EQUI_CODE IN ('40RP','20ST','40RH','40ST','20RF','40RA','40HW','40HC');

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_equipment_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :FILTER_TYPE, :RES_FILTER_ID);

END;



---------------------create time filter PAST3WEEKS--------------------------------------
BEGIN

DECLARE DESC VARCHAR(200);
DECLARE DIRECTION_FLAG INTEGER;
DECLARE CODE NVARCHAR(20) DEFAULT '';
DECLARE NAME VARCHAR(50);
DECLARE OFFSET_FLAG INTEGER;
DECLARE TIMEZONE_ID VARCHAR(50);
DECLARE HOUR_START_FROM INTEGER;
DECLARE MINUTE_START_FROM INTEGER;
DECLARE WEEK_START_FROM INTEGER;
DECLARE MONTH_START_FROM INTEGER;
DECLARE VISIBILITY CHAR(1);
DECLARE ITEM_LIST TABLE ( "UNIT" VARCHAR(22),"VALUE" INT,"REPEAT_TIME" INT,"SEQUENCE" INT );
DECLARE ITEM_UNIT VARCHAR(22) ARRAY;
DECLARE ITEM_VALUE INT ARRAY;
DECLARE ITEM_REPEAT_TIME INT ARRAY;
DECLARE ITEM_SEQUENCE INT ARRAY;

--assign values to parameters
DESC := 'Past Three Weeks';
DIRECTION_FLAG := 1;
NAME := 'PAST3WEEKS';
OFFSET_FLAG := 1;
TIMEZONE_ID := 'UTC+8';
HOUR_START_FROM := 1;
MINUTE_START_FROM := 10;
WEEK_START_FROM := 1;
MONTH_START_FROM := 1;
VISIBILITY := 'G';
--construct item list
ITEM_UNIT[1] := 'WEEK';
ITEM_VALUE[1] := 1;
ITEM_REPEAT_TIME[1] := 3;
ITEM_SEQUENCE[1] := 1;
ITEM_LIST = UNNEST(:ITEM_UNIT,:ITEM_VALUE,:ITEM_REPEAT_TIME,:ITEM_SEQUENCE) AS ("UNIT","VALUE","REPEAT_TIME","SEQUENCE");

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_time_filter_create"( :DESC, :DIRECTION_FLAG, :CODE, :NAME, :OFFSET_FLAG, :TIMEZONE_ID, 
			:HOUR_START_FROM, :MINUTE_START_FROM, :WEEK_START_FROM, :MONTH_START_FROM, :VISIBILITY, :ITEM_LIST, :TIME_FILTER_ID);



--assign values to parameters
DESC := 'Next Three Weeks';
DIRECTION_FLAG := 2;
NAME := 'NEXT3WEEKS';
OFFSET_FLAG := 1;
TIMEZONE_ID := 'UTC+8';
HOUR_START_FROM := 1;
MINUTE_START_FROM := 10;
WEEK_START_FROM := 1;
MONTH_START_FROM := 1;
VISIBILITY := 'G';
--construct item list
ITEM_UNIT[1] := 'WEEK';
ITEM_VALUE[1] := 1;
ITEM_REPEAT_TIME[1] := 3;
ITEM_SEQUENCE[1] := 1;
ITEM_LIST = UNNEST(:ITEM_UNIT,:ITEM_VALUE,:ITEM_REPEAT_TIME,:ITEM_SEQUENCE) AS ("UNIT","VALUE","REPEAT_TIME","SEQUENCE");

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_time_filter_create"( :DESC, :DIRECTION_FLAG, :CODE, :NAME, :OFFSET_FLAG, :TIMEZONE_ID, 
			:HOUR_START_FROM, :MINUTE_START_FROM, :WEEK_START_FROM, :MONTH_START_FROM, :VISIBILITY, :ITEM_LIST, :TIME_FILTER_ID);

END;


------------------------create cost model PR_REAL_COST------------------------------------
BEGIN

DECLARE NAME VARCHAR(500);
DECLARE DESC VARCHAR(500);
DECLARE LOCATION_FILTER_ID BIGINT;
DECLARE CURRENCY VARCHAR(3);
DECLARE DATA_SOURCE INTEGER;
DECLARE DATA_MISSING_FLAG INTEGER;
DECLARE ORGANIZATION_ID VARCHAR(10);
DECLARE DOCUMENT_ID VARCHAR(10);
DECLARE LOCIDS TABLE (ID NVARCHAR(22),LOCNO NVARCHAR(20));

---create cost model for HOT_LOC filter
NAME := 'PR_REAL_COST';
DESC := 'Used for P&R and resource balancing';
LOCATION_FILTER_ID := :HOT_LOC_FILTER_ID;
CURRENCY := 'EUR';
DATA_SOURCE := 1;
DATA_MISSING_FLAG := 0;
ORGANIZATION_ID := '';
DOCUMENT_ID := '';

CALL "SAP_TM_TRP"."sap.tm.trp.db.costmodel::p_ext_cost_model_create"(:NAME, :NAME, :DESC, :LOCATION_FILTER_ID, :CURRENCY, :DATA_SOURCE, 
	:DATA_MISSING_FLAG, :ORGANIZATION_ID, :DOCUMENT_ID, :COST_MODEL_ID );
	
LOCIDS = SELECT DISTINCT A.LOCID AS ID,B.LOCNO AS LOCNO FROM "SAPTMW"."/SAPAPO/LOC" AS A INNER JOIN "SAPTMW"."Z_BKLOC" AS B ON A.LOCNO = B.LOCNO WHERE A.MANDT = '800';
 
--LOC_ARR := ARRAY_AGG(:LOCIDS."ID");
LAN_TMP = SELECT B.ID AS FROM_LOCATION, A.ID AS TO_LOCATION,
CASE WHEN LEFT(A.LOCNO,2) = LEFT(B.LOCNO,2) THEN FLOOR(RAND() * 2000 + 1000) ELSE FLOOR(RAND() * 30000 + 15000) END AS COST
FROM :LOCIDS AS A, :LOCIDS AS B WHERE A.ID <> B.ID;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40RP' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40RH' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20RF' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40RA' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HW' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RP', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RH', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20RF', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RA', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HW', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;


INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RP', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RH', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20RF', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RA', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HW', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;



---create cost model for  filter
NAME := 'FR_REAL_COST';
DESC := 'Cost Model for Hot Locations in Franch';
LOCATION_FILTER_ID := :FR_LOC_FILTER_ID;
CURRENCY := 'EUR';
DATA_SOURCE := 1;
DATA_MISSING_FLAG := 0;
ORGANIZATION_ID := '';
DOCUMENT_ID := '';

CALL "SAP_TM_TRP"."sap.tm.trp.db.costmodel::p_ext_cost_model_create"(:NAME, :NAME, :DESC, :LOCATION_FILTER_ID, :CURRENCY, :DATA_SOURCE, 
    :DATA_MISSING_FLAG, :ORGANIZATION_ID, :DOCUMENT_ID, :COST_MODEL_ID );
    
LOCIDS = SELECT DISTINCT A.LOCID AS ID, A.LOCNO AS LOCNO FROM "SAPTMW"."/SAPAPO/LOC" AS A INNER JOIN "SAPTMW"."Z_BKLOC" AS B
ON A.LOCNO = B.LOCNO WHERE A.MANDT = '800' AND B.LOCNO LIKE 'FR%';

LAN_TMP = SELECT B.ID AS FROM_LOCATION, A.ID AS TO_LOCATION,
CASE WHEN LEFT(A.LOCNO,2) = LEFT(B.LOCNO,2) THEN FLOOR(RAND() * 2000 + 1000) ELSE FLOOR(RAND() * 30000 + 15000) END AS COST
FROM :LOCIDS AS A, :LOCIDS AS B WHERE A.ID <> B.ID;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40RP' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40RH' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20RF' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40RA' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HW' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'EUR' AS CURRENCY
FROM :LAN_TMP;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RP', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RH', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20RF', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RA', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HW', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'EUR'
    FROM :LOCIDS AS ITEM;


INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RP', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RH', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20RF', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40RA', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HW', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'EUR'
    FROM :LOCIDS AS ITEM;







    
END;


----------------------create default alert rule and location determination rule--------------------
BEGIN

DECLARE RULE_NAME VARCHAR(50);
DECLARE RULE_DESC VARCHAR(200);
DECLARE RULE_TYPE_ID INT;
DECLARE SP VARCHAR(200);
DECLARE FLAG INT;


--create supply demand stock alert SD_STK_AR
RULE_NAME := 'SD_STK_AR';
RULE_DESC := 'Supply Demand Stock Alert Rule';
RULE_TYPE_ID := 1;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.supplyDemand.r_supplyDemand::r_dt_SD_supplyDemand_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :SD_STOCK_ALERT_RULE_ID);

--create tor supply forecast supply SD_TSFS_AR
RULE_NAME := 'SD_TSFS_AR';
RULE_DESC := 'Supply Demand alert rule for TOR Supply/Forecast Supply';
RULE_TYPE_ID := 3;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.supplyDemand.r_supply::r_dt_SD_supply_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :SD_STOCK_ALERT_RULE_ID);


--create tor demand forecast demand SD_TDFD_AR
RULE_NAME := 'SD_TDFD_AR';
RULE_DESC := 'Supply Demand alert rule for TOR Demand/Forecast Demand';
RULE_TYPE_ID := 4;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.supplyDemand.r_demand::r_dt_SD_demand_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :SD_STOCK_ALERT_RULE_ID);



--create KPI based on quantity alert 
RULE_NAME := 'QT_KPI_AR';
RULE_DESC := 'quantity based kpi alert rule';
RULE_TYPE_ID := 7;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.kpi.r_quantity::r_dt_KPI_quantity"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :SD_STOCK_ALERT_RULE_ID);


--create supply demand forecast alert SD_FCST_AR
RULE_NAME := 'SD_FCST_AR';
RULE_DESC := 'Supply Demand Forecast Alert Rule';
RULE_TYPE_ID := 5;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.supplyDemand.r_stock::r_dt_SD_stock_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :SD_FCST_ALERT_RULE_ID);

--create idle rate based KPI alert rule IR_KPI_AR
RULE_NAME := 'IR_KPI_AR';
RULE_DESC := 'Idle Rate Based KPI Alert Rule';
RULE_TYPE_ID := 6;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.kpi.r_rate::r_dt_KPI_rate"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :IDLE_RATE_ALERT_RULE_ID);

--create location determination rule 
RULE_NAME := 'PICKUP_LDR';
RULE_DESC := 'Pickup Location Determination Rule';
RULE_TYPE_ID := 8;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.pickupReturnScenario.locationDetermination.ERLDR::r_dt_pickup_base_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :PICKUP_LDR_ID);


--create location determination rule 
RULE_NAME := 'RETURN_LDR';
RULE_DESC := 'Return Location Determination Rule';
RULE_TYPE_ID := 9;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.pickupReturnScenario.locationDetermination.ERLDR::r_dt_return_base_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :RETURN_LDR_ID);

--create resource stock alert view
RULE_NAME := 'RES_STK_AR';
RULE_DESC := 'Resource Stock Alert Rule';
RULE_TYPE_ID := 10;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.resourceStock.alertView::r_dt_stock_alertView_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:RES_STK_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('RESOURCE_STOCK_ALERT_VIEW',:RES_STK_ALERT_RULE_ID,:FLAG);

--create resource stock alert in buble view
RULE_NAME := 'RES_STK_BUB_AR';
RULE_DESC := 'Resource Stock Bubble View Alert Rule';
RULE_TYPE_ID := 11;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.resourceStock.bubbleView::r_dt_stock_bubbleView_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:RES_STK_BUB_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('RESOURCE_STOCK_BUBBLE_VIEW',:RES_STK_BUB_ALERT_RULE_ID,:FLAG);

--create sd kpi plan alert in bubble view
RULE_NAME := 'SD_KPI_BUB_AR';
RULE_DESC := 'Supply&Demand KPI Plan Bubble View Alert Rule';
RULE_TYPE_ID := 14;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.planBubble::r_dt_sd_kpi_bubble_cus"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:SD_KPI_BUB_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('SUPPLY_DEMAND_KPI_PLAN_BUBBLE_VIEW',:SD_KPI_BUB_ALERT_RULE_ID,:FLAG);

--available_check_plan
RULE_NAME := 'AVC_PLAN_AR';
RULE_DESC := 'Available Check Plan Alert Rule';
RULE_TYPE_ID := 16;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.availableCheck::r_dt_availableCheck_plan00"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:AVC_PLAN_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('AVAILABLE_CHECK_PLAN',:AVC_PLAN_ALERT_RULE_ID,:FLAG);

--available_check_level 
RULE_NAME := 'AVC_LVL_AR';
RULE_DESC := 'Available Check Level Alert Rule';
RULE_TYPE_ID := 17;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.availableCheck::r_dt_availableCheck_level00"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:AVC_LVL_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('AVAILABLE_CHECK_LEVEL',:AVC_LVL_ALERT_RULE_ID,:FLAG);



CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_register_global_default_minMaxSafetyCapacity"('MIN_SAFETY_STOCK',40,:FLAG);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_register_global_default_minMaxSafetyCapacity"('MAX_SAFETY_STOCK',200,:FLAG);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_register_global_default_minMaxSafetyCapacity"('MAX_CAPACITY',300,:FLAG);


END;


------------------------create calculation model---------------------
BEGIN

DECLARE SCHEMA_NAME VARCHAR(20);
DECLARE PROCEDURE_NAME VARCHAR(200);
DECLARE TABLE_NAME VARCHAR(200);
DECLARE PROCEDURE_DESC VARCHAR(500);
DECLARE PIPELINE_NAME VARCHAR(200);
DECLARE PIPELINE_DESC VARCHAR(500);
DECLARE PIPELINE_TYPE_ID INTEGER;
DECLARE ENTRY_ID BIGINT;

--create supply demand calculation model
SCHEMA_NAME := 'SAP_TM_TRP';
PROCEDURE_NAME := 'sap.tm.trp.db.pipeline::pipeline_supply_demand_all_w_stock';
TABLE_NAME := 'sap.tm.trp.db.pipeline::pipeline_supply_demand_all_w_stock.META';
PROCEDURE_DESC := 'Default Supply&Demand Calculation Model';
PIPELINE_NAME := 'DFT_SD_CM';
PIPELINE_DESC := 'Default Supply&Demand Calculation Model';
PIPELINE_TYPE_ID := 1;
CALL "SAP_TM_TRP"."sap.tm.trp.db.pipeline::p_register_pipeline_model"(:SCHEMA_NAME,:PROCEDURE_NAME,:TABLE_NAME,:PROCEDURE_DESC,:PIPELINE_NAME,
																	  :PIPELINE_DESC,:PIPELINE_TYPE_ID,:ENTRY_ID,:SD_PIPELINE_MODEL_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_controller_for_pipeline_model"(:SD_PIPELINE_MODEL_ID);																	  
																	  

--create idle rate based KPI calculation model
SCHEMA_NAME := 'SAP_TM_TRP';
PROCEDURE_NAME := 'sap.tm.trp.db.pipeline::kpi_idle_rate';
TABLE_NAME := 'sap.tm.trp.db.pipeline::kpi_idle_rate.META';
PROCEDURE_DESC := 'Default KPI Calculation Model';
PIPELINE_NAME := 'DFT_KPI_CM';
PIPELINE_DESC := 'Default KPI Calculation Model';
PIPELINE_TYPE_ID := 2;
CALL "SAP_TM_TRP"."sap.tm.trp.db.pipeline::p_register_pipeline_model"(:SCHEMA_NAME,:PROCEDURE_NAME,:TABLE_NAME,:PROCEDURE_DESC,:PIPELINE_NAME,
																	  :PIPELINE_DESC,:PIPELINE_TYPE_ID,:ENTRY_ID,:KPI_PIPELINE_MODEL_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_controller_for_pipeline_model"(:KPI_PIPELINE_MODEL_ID);																	  



--create kpi import export cm
SCHEMA_NAME := 'SAP_TM_TRP';
PROCEDURE_NAME := 'sap.tm.trp.db.pipeline::kpi_import_export_volume';
TABLE_NAME := 'sap.tm.trp.db.pipeline::kpi_import_export_volume.META';
PROCEDURE_DESC := 'Default KPI Import&Export Calculation Model';
PIPELINE_NAME := 'DFT_KPI_IMP_EXP_CM';
PIPELINE_DESC := 'Default KPI Import Export Calculation Model';
PIPELINE_TYPE_ID := 2;
CALL "SAP_TM_TRP"."sap.tm.trp.db.pipeline::p_register_pipeline_model"(:SCHEMA_NAME,:PROCEDURE_NAME,:TABLE_NAME,:PROCEDURE_DESC,:PIPELINE_NAME,
                                                                      :PIPELINE_DESC,:PIPELINE_TYPE_ID,:ENTRY_ID,:KPI_IMP_EXP_PIPELINE_MODEL_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_controller_for_pipeline_model"(:KPI_IMP_EXP_PIPELINE_MODEL_ID);                                                                     
    
																 
END;


------------------------create alert rule group---------------------
BEGIN

DECLARE ALERT_GROUP_NAME VARCHAR(50);
DECLARE ALERT_GROUP_DESC VARCHAR(200);
DECLARE ALERT_RULE_GROUP_CATEGORY_ID INTEGER;
DECLARE ALLOWED_USAGED_ID VARCHAR(10);
DECLARE SD_ALERT_RULE_GROUP_ID BIGINT;
DECLARE KPI_ALERT_RULE_GROUP_ID BIGINT;
DECLARE RULE_ID_LIST TABLE (RULE_ID BIGINT);
DECLARE RULE_ID_ARR BIGINT ARRAY;
DECLARE SUCCESS_FLAG INT;

--create Supply Demand Rule Group DFT_SD_AR_GRP
ALERT_GROUP_NAME := 'DFT_SD_AR_GRP';
ALERT_GROUP_DESC := 'Default Supply&Demand Alert Rule Group';
ALERT_RULE_GROUP_CATEGORY_ID := 1;
ALLOWED_USAGED_ID := 'G';

CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_create_ruleGroup" (:ALERT_GROUP_NAME,:ALERT_GROUP_DESC,:ALERT_RULE_GROUP_CATEGORY_ID,:ALLOWED_USAGED_ID,:SD_ALERT_RULE_GROUP_ID);
RULE_ID_ARR[1] := :SD_STOCK_ALERT_RULE_ID;
RULE_ID_ARR[2] := :SD_FCST_ALERT_RULE_ID;
RULE_ID_LIST = UNNEST(:RULE_ID_ARR) AS ("RULE_ID");
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_adjust_rule_group_items"(:SD_ALERT_RULE_GROUP_ID,:RULE_ID_LIST,:SUCCESS_FLAG);

--create Supply Demand Rule Group DFT_KPI_AR_GRP
ALERT_GROUP_NAME := 'DFT_KPI_AR_GRP';
ALERT_GROUP_DESC := 'Default KPI Alert Rule Group';
ALERT_RULE_GROUP_CATEGORY_ID := 2;
ALLOWED_USAGED_ID := 'G';

CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_create_ruleGroup" (:ALERT_GROUP_NAME,:ALERT_GROUP_DESC,:ALERT_RULE_GROUP_CATEGORY_ID,:ALLOWED_USAGED_ID,:KPI_ALERT_RULE_GROUP_ID);
RULE_ID_ARR := TRIM_ARRAY(:RULE_ID_ARR,2);
RULE_ID_ARR[1] := :IDLE_RATE_ALERT_RULE_ID;
RULE_ID_LIST = UNNEST(:RULE_ID_ARR) AS ("RULE_ID");
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_adjust_rule_group_items"(:KPI_ALERT_RULE_GROUP_ID,:RULE_ID_LIST,:SUCCESS_FLAG);


END;





-----------------------------------load leasing contract--------------------------------------
BEGIN

DECLARE MSG NVARCHAR(500);
DECLARE LOCNO_ARR NVARCHAR(20) ARRAY;
DECLARE ARR_INDEX INT;
DECLARE TERM_CODE INT := 1;

DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src" VALUES('2','LESSOR_AGREMENT_REFERENCE','YML','ADDRESS_LINE1',NULL,NULL,'YML',NULL,NULL,'US',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.sap.com/index.html');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src" VALUES('3','LESSOR_AGREMENT_REFERENCE','COSCO','ADDRESS_LINE1',NULL,NULL,'COSCO',NULL,NULL,'US',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.sap.com/index.html');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src" VALUES('1','LESSOR_AGREMENT_REFERENCE','MSK','ADDRESS_LINE1',NULL,NULL,'MSK',NULL,NULL,'CN',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.sap.com/index.html');
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src" VALUES('1','SHORT TERM');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src" VALUES('2','LONG TERM');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src" VALUES('3','OneWay Lease');
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('1','1005','1','1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Dec 31, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'EUR',NULL,TO_TIMESTAMP('Jul 11, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,TO_TIMESTAMP('Dec 22, 2010 9:09:01.058 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,30000,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('2','1006','2','2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Dec 31, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'EUR',NULL,TO_TIMESTAMP('Jul 11, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,TO_TIMESTAMP('Dec 22, 2010 9:09:01.058 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,30000,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('3','1007','3','3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Dec 31, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'EUR',NULL,TO_TIMESTAMP('Jul 11, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,TO_TIMESTAMP('Dec 22, 2010 9:09:01.058 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,30000,NULL,1);

--DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_condition_ext_src";
--loop location ids
--LOCNO_TAB = SELECT DISTINCT LOCNO FROM "Z_BKLOC";
--LOCNO_ARR = ARRAY_AGG(:LOCNO_TAB.LOCNO);
--FOR ARR_INDEX IN 1 .. CARDINALITY(:LOCNO_ARR) DO
---   INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_condition_ext_src" VALUES('17','1',:LOCNO_ARR[:ARR_INDEX],1,1,'40RP',10,100,1,TO_TIMESTAMP('Jan 14, 2010 2:56:17.135 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 2:56:17.135 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);

--END FOR;
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '4','1','40RP',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '5','1','20ST',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '6','1','40RH',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '7','1','40ST',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '8','1','20RF',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '9','1','40RA',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('10','1','40HW',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('11','1','40HC',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '14','2','40RP',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '15','2','20ST',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '16','2','40RH',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '17','2','40ST',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '18','2','20RF',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '19','2','40RA',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('110','2','40HW',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('111','2','40HC',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '24','3','40RP',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '25','3','20ST',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '26','3','40RH',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '27','3','40ST',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '28','3','20RF',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '29','3','40RA',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('210','3','40HW',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('211','3','40HC',1,10,TO_TIMESTAMP('Jan 14, 2010 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2099 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);

DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src";
--loop location ids
LOCNO_TAB = SELECT DISTINCT LOCNO FROM "SAPTMW"."Z_BKLOC";
LOCNO_ARR = ARRAY_AGG(:LOCNO_TAB.LOCNO);
FOR ARR_INDEX IN 1 .. CARDINALITY(:LOCNO_ARR) DO
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RP',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'20ST',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RH',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40ST',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'20RF',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RA',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40HW',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'1',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40HC',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);

    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RP',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'20ST',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RH',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40ST',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'20RF',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RA',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40HW',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'2',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40HC',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);

    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RP',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'20ST',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RH',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40ST',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'20RF',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40RA',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40HW',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
    TERM_CODE := :TERM_CODE + 1;
    INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES(TO_VARCHAR(:TERM_CODE),'3',TO_TIMESTAMP('Jan 1, 2010 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2099 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),:LOCNO_ARR[:ARR_INDEX],1,1,'40HC',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2010 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);

END FOR;

CALL "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::sp_lease_contract_data_provision"(:MSG);

END;





------------------------------set location stock

BEGIN 
DECLARE GEO_ID NVARCHAR(22);
DECLARE GEO_TYPE INTEGER DEFAULT 1;
DECLARE STOCK_SETTINGS TABLE (
     "MIN_SAFETY_STOCK" INTEGER,
     "MAX_SAFETY_STOCK" INTEGER,
     "MAX_PHYSICAL_STOCK" INTEGER);
DECLARE STOCK_THREADS TABLE (
     "RESOURCE_ID" VARCHAR(22),
     "RESOURCE_TYPE" INTEGER,
     "MIN_SAFETY_STOCK" INTEGER,
     "MAX_SAFETY_STOCK" INTEGER,
     "MAX_PHYSICAL_STOCK" INTEGER);
DECLARE LOCID_TAB TABLE (GEO_ID NVARCHAR(22));
DECLARE LOCID_ARR NVARCHAR(22) ARRAY;
DECLARE ARR_INDEX INTEGER;

GEO_TYPE := 1;
--CONSTRUCT STOCK SETTINGS
STOCK_SETTINGS = SELECT 1 AS MIN_SAFETY_STOCK, 10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY;
STOCK_THREADS = SELECT '40RP' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY;

STOCK_THREADS = SELECT '20ST' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY
UNION
SELECT RESOURCE_ID,RESOURCE_TYPE,MIN_SAFETY_STOCK,MAX_SAFETY_STOCK,MAX_PHYSICAL_STOCK FROM :STOCK_THREADS;

STOCK_THREADS = SELECT '40RH' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY
UNION
SELECT RESOURCE_ID,RESOURCE_TYPE,MIN_SAFETY_STOCK,MAX_SAFETY_STOCK,MAX_PHYSICAL_STOCK FROM :STOCK_THREADS;

STOCK_THREADS = SELECT '40ST' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY
UNION
SELECT RESOURCE_ID,RESOURCE_TYPE,MIN_SAFETY_STOCK,MAX_SAFETY_STOCK,MAX_PHYSICAL_STOCK FROM :STOCK_THREADS;

STOCK_THREADS = SELECT '20RF' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY
UNION
SELECT RESOURCE_ID,RESOURCE_TYPE,MIN_SAFETY_STOCK,MAX_SAFETY_STOCK,MAX_PHYSICAL_STOCK FROM :STOCK_THREADS;

STOCK_THREADS = SELECT '40RA' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY
UNION
SELECT RESOURCE_ID,RESOURCE_TYPE,MIN_SAFETY_STOCK,MAX_SAFETY_STOCK,MAX_PHYSICAL_STOCK FROM :STOCK_THREADS;

STOCK_THREADS = SELECT '40HW' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY
UNION
SELECT RESOURCE_ID,RESOURCE_TYPE,MIN_SAFETY_STOCK,MAX_SAFETY_STOCK,MAX_PHYSICAL_STOCK FROM :STOCK_THREADS;
STOCK_THREADS = SELECT '40HC' AS RESOURCE_ID, 1 AS RESOURCE_TYPE, 1 AS MIN_SAFETY_STOCK,
10 AS MAX_SAFETY_STOCK, 20 AS MAX_PHYSICAL_STOCK FROM DUMMY
UNION
SELECT RESOURCE_ID,RESOURCE_TYPE,MIN_SAFETY_STOCK,MAX_SAFETY_STOCK,MAX_PHYSICAL_STOCK FROM :STOCK_THREADS;

LOCID_TAB = SELECT DISTINCT LOCID AS GEO_ID FROM "SAPTMW"."Z_BKLOC" AS A
INNER JOIN "SAPTMW"."/SAPAPO/LOC" AS B ON A.LOCNO = B.LOCNO AND B.MANDT = '800';
LOCID_ARR := ARRAY_AGG(:LOCID_TAB.GEO_ID);
FOR ARR_INDEX IN 1 .. CARDINALITY(:LOCID_ARR) DO
    GEO_ID := :LOCID_ARR[:ARR_INDEX];
    CALL "SAP_TM_TRP"."sap.tm.trp.db.stock::p_location_stock_update"(
        :GEO_ID,:GEO_TYPE,:STOCK_SETTINGS,:STOCK_THREADS
        );
END FOR;

END;



END;
