CREATE USER ADM_PIETER PASSWORD Welcome0315;
CREATE USER ADM_STEFAN PASSWORD Welcome0315;
CREATE USER ADM_BUSHRA PASSWORD Welcome0315;
CREATE USER ADM_BERND PASSWORD Welcome0315;
CREATE USER ADM_ALEXEI PASSWORD Welcome0315;
CREATE USER ADM_MASSIM PASSWORD Welcome0315;
CREATE USER ADM_CHRIST PASSWORD Welcome0315;
CREATE USER ADM_RALF PASSWORD Welcome0315;
CREATE USER ADM_RODION PASSWORD Welcome0315;
CREATE USER ADM_FRANK PASSWORD Welcome0315;
CREATE USER ADM_SERGEY PASSWORD Welcome0315;
CREATE USER ADM_ALEXAN PASSWORD Welcome0315;
CREATE USER ADM_FRANZ PASSWORD Welcome0315;
CREATE USER ADM_HANNA PASSWORD Welcome0315;
CREATE USER ADM_EMANUEL PASSWORD Welcome0315;
CREATE USER ADM_CARSTEN PASSWORD Welcome0315;
CREATE USER ADM_GERHARD PASSWORD Welcome0315;
CREATE USER ADM_MALTE PASSWORD Welcome0315;
CREATE USER ADM_DOMINIK PASSWORD Welcome0315;
CREATE USER ADM_LEONARD PASSWORD Welcome0315;
CREATE USER ADM_BAHADIR PASSWORD Welcome0315;
CREATE USER ADM_JEROEN PASSWORD Welcome0315;
CREATE USER ADM_JOHN PASSWORD Welcome0315;
CREATE USER DM_PIETER PASSWORD Welcome0315;
CREATE USER DM_STEFAN PASSWORD Welcome0315;
CREATE USER DM_BUSHRA PASSWORD Welcome0315;
CREATE USER DM_BERND PASSWORD Welcome0315;
CREATE USER DM_ALEXEI PASSWORD Welcome0315;
CREATE USER DM_MASSIM PASSWORD Welcome0315;
CREATE USER DM_CHRIST PASSWORD Welcome0315;
CREATE USER DM_RALF PASSWORD Welcome0315;
CREATE USER DM_RODION PASSWORD Welcome0315;
CREATE USER DM_FRANK PASSWORD Welcome0315;
CREATE USER DM_SERGEY PASSWORD Welcome0315;
CREATE USER DM_ALEXAN PASSWORD Welcome0315;
CREATE USER DM_FRANZ PASSWORD Welcome0315;
CREATE USER DM_HANNA PASSWORD Welcome0315;
CREATE USER DM_EMANUEL PASSWORD Welcome0315;
CREATE USER DM_CARSTEN PASSWORD Welcome0315;
CREATE USER DM_GERHARD PASSWORD Welcome0315;
CREATE USER DM_MALTE PASSWORD Welcome0315;
CREATE USER DM_DOMINIK PASSWORD Welcome0315;
CREATE USER DM_LEONARD PASSWORD Welcome0315;
CREATE USER DM_BAHADIR PASSWORD Welcome0315;
CREATE USER DM_JEROEN PASSWORD Welcome0315;
CREATE USER DM_JOHN PASSWORD Welcome0315;
CREATE USER RP_PIETER PASSWORD Welcome0315;
CREATE USER RP_STEFAN PASSWORD Welcome0315;
CREATE USER RP_BUSHRA PASSWORD Welcome0315;
CREATE USER RP_BERND PASSWORD Welcome0315;
CREATE USER RP_ALEXEI PASSWORD Welcome0315;
CREATE USER RP_MASSIM PASSWORD Welcome0315;
CREATE USER RP_CHRIST PASSWORD Welcome0315;
CREATE USER RP_RALF PASSWORD Welcome0315;
CREATE USER RP_RODION PASSWORD Welcome0315;
CREATE USER RP_FRANK PASSWORD Welcome0315;
CREATE USER RP_SERGEY PASSWORD Welcome0315;
CREATE USER RP_ALEXAN PASSWORD Welcome0315;
CREATE USER RP_FRANZ PASSWORD Welcome0315;
CREATE USER RP_HANNA PASSWORD Welcome0315;
CREATE USER RP_EMANUEL PASSWORD Welcome0315;
CREATE USER RP_CARSTEN PASSWORD Welcome0315;
CREATE USER RP_GERHARD PASSWORD Welcome0315;
CREATE USER RP_MALTE PASSWORD Welcome0315;
CREATE USER RP_DOMINIK PASSWORD Welcome0315;
CREATE USER RP_LEONARD PASSWORD Welcome0315;
CREATE USER RP_BAHADIR PASSWORD Welcome0315;
CREATE USER RP_JEROEN PASSWORD Welcome0315;
CREATE USER RP_JOHN PASSWORD Welcome0315;





CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_PIETER');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_STEFAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_BUSHRA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_BERND');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_ALEXEI');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_MASSIM');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_CHRIST');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_RALF');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_RODION');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_FRANK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_SERGEY');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_ALEXAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_FRANZ');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_HANNA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_EMANUEL');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_CARSTEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_GERHARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_MALTE');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_DOMINIK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_LEONARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_BAHADIR');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_JEROEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::admin_trp','ADM_JOHN');

CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_PIETER');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_STEFAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_BUSHRA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_BERND');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_ALEXEI');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_MASSIM');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_CHRIST');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_RALF');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_RODION');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_FRANK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_SERGEY');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_ALEXAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_FRANZ');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_HANNA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_EMANUEL');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_CARSTEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_GERHARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_MALTE');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_DOMINIK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_LEONARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_BAHADIR');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_JEROEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::developer','ADM_JOHN');

CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_PIETER');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_STEFAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_BUSHRA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_BERND');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_ALEXEI');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_MASSIM');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_CHRIST');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_RALF');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_RODION');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_FRANK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_SERGEY');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_ALEXAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_FRANZ');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_HANNA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_EMANUEL');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_CARSTEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_GERHARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_MALTE');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_DOMINIK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_LEONARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_BAHADIR');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_JEROEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::depot_trp','DM_JOHN');

CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_PIETER');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_STEFAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_BUSHRA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_BERND');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_ALEXEI');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_MASSIM');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_CHRIST');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_RALF');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_RODION');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_FRANK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_SERGEY');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_ALEXAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_FRANZ');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_HANNA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_EMANUEL');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_CARSTEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_GERHARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_MALTE');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_DOMINIK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_LEONARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_BAHADIR');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_JEROEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('sap.tm.trp.config::regional_trp','RP_JOHN');

CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_PIETER');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_STEFAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_BUSHRA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_BERND');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_ALEXEI');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_MASSIM');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_CHRIST');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_RALF');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_RODION');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_FRANK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_SERGEY');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_ALEXAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_FRANZ');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_HANNA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_EMANUEL');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_CARSTEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_GERHARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_MALTE');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_DOMINIK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_LEONARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_BAHADIR');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_JEROEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','ADM_JOHN');

CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_PIETER');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_STEFAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_BUSHRA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_BERND');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_ALEXEI');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_MASSIM');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_CHRIST');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_RALF');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_RODION');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_FRANK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_SERGEY');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_ALEXAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_FRANZ');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_HANNA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_EMANUEL');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_CARSTEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_GERHARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_MALTE');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_DOMINIK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_LEONARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_BAHADIR');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_JEROEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','DM_JOHN');

CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_PIETER');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_STEFAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_BUSHRA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_BERND');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_ALEXEI');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_MASSIM');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_CHRIST');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_RALF');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_RODION');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_FRANK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_SERGEY');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_ALEXAN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_FRANZ');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_HANNA');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_EMANUEL');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_CARSTEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_GERHARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_MALTE');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_DOMINIK');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_LEONARD');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_BAHADIR');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_JEROEN');
CALL "_SYS_REPO"."GRANT_ACTIVATED_ROLE"('trp_preset::query_y0m','RP_JOHN');

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_PIETER',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_STEFAN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_BUSHRA',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_BERND',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_ALEXEI',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_MASSIM',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_CHRIST',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_RALF',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_RODION',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_FRANK',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_SERGEY',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_ALEXAN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_FRANZ',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_HANNA',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_EMANUEL',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_CARSTEN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_GERHARD',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_MALTE',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_DOMINIK',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_LEONARD',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_BAHADIR',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_JEROEN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('ADM_JOHN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_PIETER',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_STEFAN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_BUSHRA',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_BERND',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_ALEXEI',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_MASSIM',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_CHRIST',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_RALF',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_RODION',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_FRANK',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_SERGEY',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_ALEXAN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_FRANZ',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_HANNA',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_EMANUEL',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_CARSTEN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_GERHARD',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_MALTE',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_DOMINIK',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_LEONARD',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_BAHADIR',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_JEROEN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('DM_JOHN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_PIETER',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_STEFAN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_BUSHRA',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_BERND',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_ALEXEI',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_MASSIM',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_CHRIST',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_RALF',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_RODION',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_FRANK',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_SERGEY',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_ALEXAN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_FRANZ',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_HANNA',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_EMANUEL',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_CARSTEN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_GERHARD',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_MALTE',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_DOMINIK',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_LEONARD',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_BAHADIR',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_JEROEN',-40);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.stock::t_start_time_for_user" VALUES ('RP_JOHN',-40);

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9001,'ADM_PIETER','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9002,'ADM_STEFAN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9003,'ADM_BUSHRA','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9004,'ADM_BERND','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9005,'ADM_ALEXEI','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9006,'ADM_MASSIM','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9007,'ADM_CHRIST','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9008,'ADM_RALF','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9009,'ADM_RODION','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9010,'ADM_FRANK','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9011,'ADM_SERGEY','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9012,'ADM_ALEXAN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9013,'ADM_FRANZ','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9014,'ADM_HANNA','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9015,'ADM_EMANUEL','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9016,'ADM_CARSTEN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9017,'ADM_GERHARD','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9018,'ADM_MALTE','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9019,'ADM_DOMINIK','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9020,'ADM_LEONARD','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9021,'ADM_BAHADIR','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9022,'ADM_JEROEN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9023,'ADM_JOHN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',99,'E',1,1,'');

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9024,'DM_PIETER','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9025,'DM_STEFAN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9026,'DM_BUSHRA','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9027,'DM_BERND','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9028,'DM_ALEXEI','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9029,'DM_MASSIM','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9030,'DM_CHRIST','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9031,'DM_RALF','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9032,'DM_RODION','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9033,'DM_FRANK','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9034,'DM_SERGEY','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9035,'DM_ALEXAN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9036,'DM_FRANZ','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9037,'DM_HANNA','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9038,'DM_EMANUEL','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9039,'DM_CARSTEN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9040,'DM_GERHARD','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9041,'DM_MALTE','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9042,'DM_DOMINIK','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9043,'DM_LEONARD','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9044,'DM_BAHADIR','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9045,'DM_JEROEN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9046,'DM_JOHN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',1,'E',1,1,'');

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9047,'RP_PIETER','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9048,'RP_STEFAN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9049,'RP_BUSHRA','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9050,'RP_BERND','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9051,'RP_ALEXEI','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9052,'RP_MASSIM','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9053,'RP_CHRIST','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9054,'RP_RALF','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9055,'RP_RODION','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9056,'RP_FRANK','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9057,'RP_SERGEY','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9058,'RP_ALEXAN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9059,'RP_FRANZ','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9060,'RP_HANNA','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9061,'RP_EMANUEL','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9062,'RP_CARSTEN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9063,'RP_GERHARD','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9064,'RP_MALTE','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9065,'RP_DOMINIK','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9066,'RP_LEONARD','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9067,'RP_BAHADIR','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9068,'RP_JEROEN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement.user::t_user" VALUES (9069,'RP_JOHN','','Jr.','','','','',TO_TIMESTAMP('20150106042628','YYYYMMDDHH24MISS'),1,4,3,'FA','UTC+1','G','CM','81','91','4G','sap_bluecrystal','800',3,'E',1,1,'');



