CREATE PROCEDURE "SAP_TM_TRP"."P_CREATE_TRP_SAMPLE_DATA" ()
AS

BEGIN
---global variables definitions
DECLARE HOT_LOC_FILTER_ID BIGINT;
DECLARE CN_LOC_FILTER_ID BIGINT;
DECLARE US_LOC_FILTER_ID BIGINT;
DECLARE FR_LOC_FILTER_ID BIGINT;
DECLARE REG_CN_FILTER_ID BIGINT;
DECLARE REG_US_FILTER_ID BIGINT;
DECLARE REG_FR_FILTER_ID BIGINT;
DECLARE RES_FILTER_ID BIGINT;
DECLARE SCHED_LOC_FILTER_ID BIGINT;
DECLARE TIME_FILTER_ID BIGINT; 
DECLARE COST_MODEL_ID BIGINT;
DECLARE SD_STOCK_ALERT_RULE_ID BIGINT;
DECLARE SD_FCST_ALERT_RULE_ID BIGINT;
DECLARE IDLE_RATE_ALERT_RULE_ID BIGINT;
DECLARE PICKUP_LDR_ID BIGINT;
DECLARE RETURN_LDR_ID BIGINT;
DECLARE RES_STK_ALERT_RULE_ID BIGINT;
DECLARE RES_STK_BUB_ALERT_RULE_ID BIGINT;
DECLARE SD_KPI_BUB_ALERT_RULE_ID BIGINT;
DECLARE AVC_PLAN_ALERT_RULE_ID BIGINT;
DECLARE AVC_LVL_ALERT_RULE_ID BIGINT;
--DECLARE QTT_ALERT_RULE_ID BIGINT;
DECLARE SD_PIPELINE_MODEL_ID BIGINT;
DECLARE KPI_PIPELINE_MODEL_ID BIGINT;
DECLARE SD_ALERT_RULE_GROUP_ID BIGINT;
DECLARE KPI_ALERT_RULE_GROUP_ID BIGINT;

-----------------create location filter ----------------------------------
BEGIN 

DECLARE NAME VARCHAR(50);
DECLARE DESC VARCHAR(500);
DECLARE VISIBLE_FLAG VARCHAR(3);
DECLARE ITEMS TABLE (ID NVARCHAR(22));
DECLARE LOCATION_TYPE INT;

--assign values to input parameters
NAME := 'SCHED_LOCS';
DESC := 'Locations included in schedules';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
ITEMS = SELECT DISTINCT A.LOCID AS ID FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A 
INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID
INNER JOIN "SAPX0M"."/SCMTMS/D_SCHLOC" AS C ON B.LOCNO = C.LOC_ID;
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :SCHED_LOC_FILTER_ID);


--assign values to input parameters
NAME := 'HOT_LOCS';
DESC := 'Locations in China, US and Franch';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
ITEMS = SELECT DISTINCT A.LOCID AS ID FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID;

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :HOT_LOC_FILTER_ID);

--assign values to input parameters
NAME := 'CN_LOCS';
DESC := 'Locations in China';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
ITEMS = SELECT DISTINCT A.LOCID AS ID FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID WHERE B.LOCNO LIKE 'CN%';
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :CN_LOC_FILTER_ID);

--assign values to input parameters
NAME := 'US_LOCS';
DESC := 'Locations in USA';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
ITEMS = SELECT DISTINCT A.LOCID AS ID FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID WHERE B.LOCNO LIKE 'US%';
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :US_LOC_FILTER_ID);

--assign values to input parameters
NAME := 'FR_LOCS';
DESC := 'Locations in France';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 1;
ITEMS = SELECT DISTINCT A.LOCID AS ID FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID WHERE B.LOCNO LIKE 'FR%';
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :FR_LOC_FILTER_ID);


NAME := 'REG_CN';
DESC := 'Part Regions Included in China';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 5;
ITEMS = SELECT SCUGUID22 AS ID FROM "SAPTM"."/SCMB/TOENTITY" WHERE ENTITY IN ('142','165','176','50');
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :REG_CN_FILTER_ID);
--assign values to input parameters
NAME := 'REG_US';
DESC := 'Part Regions Included in USA';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 5;
ITEMS = SELECT SCUGUID22 AS ID FROM "SAPTM"."/SCMB/TOENTITY" WHERE ENTITY IN ('EST','GLF','MDW','WST');
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :REG_US_FILTER_ID);
--assign values to input parameters
NAME := 'REG_FR';
DESC := 'Part Regions Included in France';
VISIBLE_FLAG := 'G';
LOCATION_TYPE := 5;
ITEMS = SELECT SCUGUID22 AS ID FROM "SAPTM"."/SCMB/TOENTITY" WHERE ENTITY IN ('FRLEH','FRMRS','FRMTX','115');
CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_location_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :LOCATION_TYPE, :REG_FR_FILTER_ID);




END;


-------------------create resource filter STHCRES----------------------------------
BEGIN

DECLARE NAME VARCHAR(50);
DECLARE DESC VARCHAR(500);
DECLARE VISIBLE_FLAG VARCHAR(3);
DECLARE ITEMS TABLE (ID NVARCHAR(22));
DECLARE FILTER_TYPE INT;
--assign valuess to input parameters
NAME := 'STHCRES';
DESC := 'ST,HC resources';
FILTER_TYPE := 1;
VISIBLE_FLAG := 'G';

ITEMS = SELECT DISTINCT T1.EQUI_CODE AS ID FROM "SAPX0M"."/SCMB/EQUI_CODE" T1 INNER JOIN "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement::v_client_code" CC 
ON T1.MANDT = CC.MANDT WHERE T1.EQUI_CODE LIKE '%0ST' OR T1.EQUI_CODE LIKE '%0HC';

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_ext_equipment_filter_create"(:NAME, :DESC, :VISIBLE_FLAG, :ITEMS, :FILTER_TYPE, :RES_FILTER_ID);

END;



---------------------create time filter PAST3WEEKS--------------------------------------
BEGIN

DECLARE DESC VARCHAR(200);
DECLARE DIRECTION_FLAG INTEGER;
DECLARE CODE NVARCHAR(20) DEFAULT '';
DECLARE NAME VARCHAR(50);
DECLARE OFFSET_FLAG INTEGER;
DECLARE TIMEZONE_ID VARCHAR(50);
DECLARE HOUR_START_FROM INTEGER;
DECLARE MINUTE_START_FROM INTEGER;
DECLARE WEEK_START_FROM INTEGER;
DECLARE MONTH_START_FROM INTEGER;
DECLARE VISIBILITY CHAR(1);
DECLARE ITEM_LIST TABLE ( "UNIT" VARCHAR(22),"VALUE" INT,"REPEAT_TIME" INT,"SEQUENCE" INT );
DECLARE ITEM_UNIT VARCHAR(22) ARRAY;
DECLARE ITEM_VALUE INT ARRAY;
DECLARE ITEM_REPEAT_TIME INT ARRAY;
DECLARE ITEM_SEQUENCE INT ARRAY;

--assign values to parameters
DESC := 'Past Three Weeks';
DIRECTION_FLAG := 1;
NAME := 'PAST3WEEKS';
OFFSET_FLAG := 1;
TIMEZONE_ID := 'UTC+8';
HOUR_START_FROM := 1;
MINUTE_START_FROM := 10;
WEEK_START_FROM := 1;
MONTH_START_FROM := 1;
VISIBILITY := 'G';
--construct item list
ITEM_UNIT[1] := 'WEEK';
ITEM_VALUE[1] := 1;
ITEM_REPEAT_TIME[1] := 3;
ITEM_SEQUENCE[1] := 1;
ITEM_LIST = UNNEST(:ITEM_UNIT,:ITEM_VALUE,:ITEM_REPEAT_TIME,:ITEM_SEQUENCE) AS ("UNIT","VALUE","REPEAT_TIME","SEQUENCE");

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_time_filter_create"( :DESC, :DIRECTION_FLAG, :CODE, :NAME, :OFFSET_FLAG, :TIMEZONE_ID, 
			:HOUR_START_FROM, :MINUTE_START_FROM, :WEEK_START_FROM, :MONTH_START_FROM, :VISIBILITY, :ITEM_LIST, :TIME_FILTER_ID);



--assign values to parameters
DESC := 'Next Three Weeks';
DIRECTION_FLAG := 2;
NAME := 'NEXT3WEEKS';
OFFSET_FLAG := 1;
TIMEZONE_ID := 'UTC+8';
HOUR_START_FROM := 1;
MINUTE_START_FROM := 10;
WEEK_START_FROM := 1;
MONTH_START_FROM := 1;
VISIBILITY := 'G';
--construct item list
ITEM_UNIT[1] := 'WEEK';
ITEM_VALUE[1] := 1;
ITEM_REPEAT_TIME[1] := 3;
ITEM_SEQUENCE[1] := 1;
ITEM_LIST = UNNEST(:ITEM_UNIT,:ITEM_VALUE,:ITEM_REPEAT_TIME,:ITEM_SEQUENCE) AS ("UNIT","VALUE","REPEAT_TIME","SEQUENCE");

CALL "SAP_TM_TRP"."sap.tm.trp.db.filter::p_time_filter_create"( :DESC, :DIRECTION_FLAG, :CODE, :NAME, :OFFSET_FLAG, :TIMEZONE_ID, 
			:HOUR_START_FROM, :MINUTE_START_FROM, :WEEK_START_FROM, :MONTH_START_FROM, :VISIBILITY, :ITEM_LIST, :TIME_FILTER_ID);

END;


------------------------create cost model PR_REAL_COST------------------------------------
BEGIN

DECLARE NAME VARCHAR(500);
DECLARE DESC VARCHAR(500);
DECLARE LOCATION_FILTER_ID BIGINT;
DECLARE CURRENCY VARCHAR(3);
DECLARE DATA_SOURCE INTEGER;
DECLARE DATA_MISSING_FLAG INTEGER;
DECLARE ORGANIZATION_ID VARCHAR(10);
DECLARE DOCUMENT_ID VARCHAR(10);
DECLARE LOCIDS TABLE (ID NVARCHAR(22),LOCNO NVARCHAR(20));
--DECLARE LOC_ARR NVARCHAR(22) ARRAY;
--DECLARE LOC_INDEX INT;

NAME := 'SCHED_LOCS_COST';
DESC := 'Schedule Lines Cost Between Locations';
LOCATION_FILTER_ID := :SCHED_LOC_FILTER_ID;
CURRENCY := 'CNY';
DATA_SOURCE := 1;
DATA_MISSING_FLAG := 0;
ORGANIZATION_ID := '';
DOCUMENT_ID := '';

CALL "SAP_TM_TRP"."sap.tm.trp.db.costmodel::p_ext_cost_model_create"(:NAME, :NAME, :DESC, :LOCATION_FILTER_ID, :CURRENCY, :DATA_SOURCE, 
	:DATA_MISSING_FLAG, :ORGANIZATION_ID, :DOCUMENT_ID, :COST_MODEL_ID );
	
LOCIDS = SELECT DISTINCT A.LOCID AS ID, C.LOC_ID AS LOCNO FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID
INNER JOIN "SAPX0M"."/SCMTMS/D_SCHLOC" AS C ON B.LOCNO = C.LOC_ID;
	
--LOC_ARR := ARRAY_AGG(:LOCIDS."ID");
LAN_TMP = SELECT B.ID AS FROM_LOCATION, A.ID AS TO_LOCATION,
CASE WHEN LEFT(A.LOCNO,2) = LEFT(B.LOCNO,2) THEN FLOOR(RAND() * 2000 + 1000) ELSE FLOOR(RAND() * 30000 + 15000) END AS COST
FROM :LOCIDS AS A, :LOCIDS AS B WHERE A.ID <> B.ID;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;



INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;


INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;



---create cost model for HOT_LOC filter
NAME := 'PR_REAL_COST';
DESC := 'Used for P&R and resource balancing';
LOCATION_FILTER_ID := :HOT_LOC_FILTER_ID;
CURRENCY := 'CNY';
DATA_SOURCE := 1;
DATA_MISSING_FLAG := 0;
ORGANIZATION_ID := '';
DOCUMENT_ID := '';

CALL "SAP_TM_TRP"."sap.tm.trp.db.costmodel::p_ext_cost_model_create"(:NAME, :NAME, :DESC, :LOCATION_FILTER_ID, :CURRENCY, :DATA_SOURCE, 
	:DATA_MISSING_FLAG, :ORGANIZATION_ID, :DOCUMENT_ID, :COST_MODEL_ID );
	
LOCIDS = SELECT DISTINCT A.LOCID AS ID,B.LOCNO AS LOCNO FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID;
	
--LOC_ARR := ARRAY_AGG(:LOCIDS."ID");
LAN_TMP = SELECT B.ID AS FROM_LOCATION, A.ID AS TO_LOCATION,
CASE WHEN LEFT(A.LOCNO,2) = LEFT(B.LOCNO,2) THEN FLOOR(RAND() * 2000 + 1000) ELSE FLOOR(RAND() * 30000 + 15000) END AS COST
FROM :LOCIDS AS A, :LOCIDS AS B WHERE A.ID <> B.ID;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;



INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;


INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
    
    
    
    
    
--create China cost model
NAME := 'CN_REAL_COST';
DESC := 'Used for P&R and resource balancing for China Internal Transportation';
LOCATION_FILTER_ID := :CN_LOC_FILTER_ID;
CURRENCY := 'CNY';
DATA_SOURCE := 1;
DATA_MISSING_FLAG := 0;
ORGANIZATION_ID := '';
DOCUMENT_ID := '';

CALL "SAP_TM_TRP"."sap.tm.trp.db.costmodel::p_ext_cost_model_create"(:NAME, :NAME, :DESC, :LOCATION_FILTER_ID, :CURRENCY, :DATA_SOURCE, 
	:DATA_MISSING_FLAG, :ORGANIZATION_ID, :DOCUMENT_ID, :COST_MODEL_ID );
	
LOCIDS = SELECT DISTINCT A.LOCID AS ID,B.LOCNO AS LOCNO FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID WHERE B.LOCNO LIKE 'CN%';
	
--LOC_ARR := ARRAY_AGG(:LOCIDS."ID");
LAN_TMP = SELECT B.ID AS FROM_LOCATION, A.ID AS TO_LOCATION,
CASE WHEN LEFT(A.LOCNO,2) = LEFT(B.LOCNO,2) THEN FLOOR(RAND() * 2000 + 1000) ELSE FLOOR(RAND() * 30000 + 15000) END AS COST
FROM :LOCIDS AS A, :LOCIDS AS B WHERE A.ID <> B.ID;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;



INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;


INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;



    
--create USA cost model
NAME := 'US_REAL_COST';
DESC := 'Used for P&R and resource balancing for USA Internal Transportation';
LOCATION_FILTER_ID := :US_LOC_FILTER_ID;
CURRENCY := 'AUD';
DATA_SOURCE := 1;
DATA_MISSING_FLAG := 0;
ORGANIZATION_ID := '';
DOCUMENT_ID := '';

CALL "SAP_TM_TRP"."sap.tm.trp.db.costmodel::p_ext_cost_model_create"(:NAME, :NAME, :DESC, :LOCATION_FILTER_ID, :CURRENCY, :DATA_SOURCE, 
	:DATA_MISSING_FLAG, :ORGANIZATION_ID, :DOCUMENT_ID, :COST_MODEL_ID );
	
LOCIDS = SELECT DISTINCT A.LOCID AS ID,B.LOCNO AS LOCNO FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID WHERE B.LOCNO LIKE 'US%';
	
--LOC_ARR := ARRAY_AGG(:LOCIDS."ID");
LAN_TMP = SELECT B.ID AS FROM_LOCATION, A.ID AS TO_LOCATION,
CASE WHEN LEFT(A.LOCNO,2) = LEFT(B.LOCNO,2) THEN FLOOR(RAND() * 2000 + 1000) ELSE FLOOR(RAND() * 30000 + 15000) END AS COST
FROM :LOCIDS AS A, :LOCIDS AS B WHERE A.ID <> B.ID;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;



INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;


INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;    
    
    
    
    
--create France cost model
NAME := 'FR_REAL_COST';
DESC := 'Used for P&R and resource balancing for France Internal Transportation';
LOCATION_FILTER_ID := :FR_LOC_FILTER_ID;
CURRENCY := 'EUR';
DATA_SOURCE := 1;
DATA_MISSING_FLAG := 0;
ORGANIZATION_ID := '';
DOCUMENT_ID := '';

CALL "SAP_TM_TRP"."sap.tm.trp.db.costmodel::p_ext_cost_model_create"(:NAME, :NAME, :DESC, :LOCATION_FILTER_ID, :CURRENCY, :DATA_SOURCE, 
	:DATA_MISSING_FLAG, :ORGANIZATION_ID, :DOCUMENT_ID, :COST_MODEL_ID );
	
LOCIDS = SELECT DISTINCT A.LOCID AS ID,B.LOCNO AS LOCNO FROM "SAPX0M"."/SAPAPO/LOC_EQUI" AS A INNER JOIN "SAPX0M"."/SAPAPO/LOC" AS B ON A.LOCID = B.LOCID WHERE B.LOCNO LIKE 'FR%';
	
--LOC_ARR := ARRAY_AGG(:LOCIDS."ID");
LAN_TMP = SELECT B.ID AS FROM_LOCATION, A.ID AS TO_LOCATION,
CASE WHEN LEFT(A.LOCNO,2) = LEFT(B.LOCNO,2) THEN FLOOR(RAND() * 2000 + 1000) ELSE FLOOR(RAND() * 30000 + 15000) END AS COST
FROM :LOCIDS AS A, :LOCIDS AS B WHERE A.ID <> B.ID;

INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40ST' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '10HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '20HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '30HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_transportation_cost"(COST_MODEL_ID, EQUIPMENT_ID,FROM_LOCATION, TO_LOCATION, CARRIER_ID, TRANSPORT_MODE, COST, CURRENCY)
SELECT :COST_MODEL_ID AS COST_MODEL_ID, '40HC' AS EQUIPMENT_ID, FROM_LOCATION, TO_LOCATION, 'CARRIER_S' AS CARRIER_ID, '01' AS TRANSPORT_MODE, 
COST, 'CNY' AS CURRENCY
FROM :LAN_TMP;



INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_handling_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, FROM_MODE, TO_MODE, TYPE, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, '01', '01', '', FLOOR(RAND() * 600 + 200), 'CNY'
    FROM :LOCIDS AS ITEM;


INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40ST', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '10HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '20HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '30HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.costmodel::t_time_base_storage_cost"
    (COST_MODEL_ID, EQUIPMENT_ID, LOCATION_ID, THRESHOLD_FROM, THRESHOLD_TO, COST, CURRENCY)
    SELECT :COST_MODEL_ID, '40HC', ITEM.ID, 1, NULL, FLOOR(RAND() * 20 + 10), 'CNY'
    FROM :LOCIDS AS ITEM;      

  
END;


----------------------create default alert rule and location determination rule--------------------
BEGIN

DECLARE RULE_NAME VARCHAR(50);
DECLARE RULE_DESC VARCHAR(200);
DECLARE RULE_TYPE_ID INT;
DECLARE SP VARCHAR(200);
DECLARE FLAG INT;


--create supply demand stock alert SD_STK_AR
RULE_NAME := 'SD_STK_AR';
RULE_DESC := 'Supply Demand Stock Alert Rule';
RULE_TYPE_ID := 1;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.supplyDemand.r_supplyDemand::r_dt_SD_supplyDemand_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :SD_STOCK_ALERT_RULE_ID);

--create supply demand forecast alert SD_FCST_AR
RULE_NAME := 'SD_FCST_AR';
RULE_DESC := 'Supply Demand Forecast Alert Rule';
RULE_TYPE_ID := 5;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.supplyDemand.r_stock::r_dt_SD_stock_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :SD_FCST_ALERT_RULE_ID);

--create idle rate based KPI alert rule IR_KPI_AR
RULE_NAME := 'IR_KPI_AR';
RULE_DESC := 'Idle Rate Based KPI Alert Rule';
RULE_TYPE_ID := 6;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.kpi.r_rate::r_dt_KPI_rate"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :IDLE_RATE_ALERT_RULE_ID);

--create quantity based KPI alert rule
--RULE_NAME := 'QTT_KPI_AR';
--RULE_DESC := 'Quantity Based KPI Alert Rule';
--RULE_TYPE_ID := 7;
--SP := '"SAP_HRF"."sap.tm.trp.db.hrf.kpi.r_quantity::r_dt_KPI_quantity"';
--CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :QTT_ALERT_RULE_ID);

--create location determination rule 
RULE_NAME := 'PICKUP_LDR';
RULE_DESC := 'Pickup Location Determination Rule';
RULE_TYPE_ID := 8;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.pickupReturnScenario.locationDetermination.ERLDR::r_dt_pickup_base_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :PICKUP_LDR_ID);


--create location determination rule 
RULE_NAME := 'RETURN_LDR';
RULE_DESC := 'Return Location Determination Rule';
RULE_TYPE_ID := 9;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.pickupReturnScenario.locationDetermination.ERLDR::r_dt_return_base_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule"(:RULE_NAME, :RULE_DESC, :RULE_TYPE_ID, :SP, :RETURN_LDR_ID);

--create resource stock alert view
RULE_NAME := 'RES_STK_AR';
RULE_DESC := 'Resource Stock Alert Rule';
RULE_TYPE_ID := 10;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.resourceStock.alertView::r_dt_stock_alertView_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:RES_STK_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('RESOURCE_STOCK_ALERT_VIEW',:RES_STK_ALERT_RULE_ID,:FLAG);

--create resource stock alert in buble view
RULE_NAME := 'RES_STK_BUB_AR';
RULE_DESC := 'Resource Stock Bubble View Alert Rule';
RULE_TYPE_ID := 11;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.resourceStock.bubbleView::r_dt_stock_bubbleView_default"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:RES_STK_BUB_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('RESOURCE_STOCK_BUBBLE_VIEW',:RES_STK_BUB_ALERT_RULE_ID,:FLAG);

--create sd kpi plan alert in bubble view
RULE_NAME := 'SD_KPI_BUB_AR';
RULE_DESC := 'Supply&Demand KPI Plan Bubble View Alert Rule';
RULE_TYPE_ID := 14;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.planBubble::r_dt_sd_kpi_bubble_cus"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:SD_KPI_BUB_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('SUPPLY_DEMAND_KPI_PLAN_BUBBLE_VIEW',:SD_KPI_BUB_ALERT_RULE_ID,:FLAG);

--available_check_plan
RULE_NAME := 'AVC_PLAN_AR';
RULE_DESC := 'Available Check Plan Alert Rule';
RULE_TYPE_ID := 16;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.availableCheck::r_dt_availableCheck_plan00"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:AVC_PLAN_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('AVAILABLE_CHECK_PLAN',:AVC_PLAN_ALERT_RULE_ID,:FLAG);

--available_check_level 
RULE_NAME := 'AVC_LVL_AR';
RULE_DESC := 'Available Check Level Alert Rule';
RULE_TYPE_ID := 17;
SP := '"SAP_HRF"."sap.tm.trp.db.hrf.availableCheck::r_dt_availableCheck_level00"';
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_TRPRule_of_new_created_HRFRule" (:RULE_NAME,:RULE_DESC,:RULE_TYPE_ID,:SP,:AVC_LVL_ALERT_RULE_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage::p_assign_rule"('AVAILABLE_CHECK_LEVEL',:AVC_LVL_ALERT_RULE_ID,:FLAG);





END;


------------------------create calculation model---------------------
BEGIN

DECLARE SCHEMA_NAME VARCHAR(20);
DECLARE PROCEDURE_NAME VARCHAR(200);
DECLARE TABLE_NAME VARCHAR(200);
DECLARE PROCEDURE_DESC VARCHAR(500);
DECLARE PIPELINE_NAME VARCHAR(200);
DECLARE PIPELINE_DESC VARCHAR(500);
DECLARE PIPELINE_TYPE_ID INTEGER;
DECLARE ENTRY_ID BIGINT;

--create supply demand calculation model
SCHEMA_NAME := 'SAP_TM_TRP';
PROCEDURE_NAME := 'sap.tm.trp.db.pipeline::pipeline_supply_demand_all_w_stock';
TABLE_NAME := 'sap.tm.trp.db.pipeline::pipeline_supply_demand_all_w_stock.META';
PROCEDURE_DESC := 'Default Supply&Demand Calculation Model';
PIPELINE_NAME := 'DFT_SD_CM';
PIPELINE_DESC := 'Default Supply&Demand Calculation Model';
PIPELINE_TYPE_ID := 1;
CALL "SAP_TM_TRP"."sap.tm.trp.db.pipeline::p_register_pipeline_model"(:SCHEMA_NAME,:PROCEDURE_NAME,:TABLE_NAME,:PROCEDURE_DESC,:PIPELINE_NAME,
																	  :PIPELINE_DESC,:PIPELINE_TYPE_ID,:ENTRY_ID,:SD_PIPELINE_MODEL_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_controller_for_pipeline_model"(:SD_PIPELINE_MODEL_ID);																	  
																	  

--create idle rate based KPI calculation model
SCHEMA_NAME := 'SAP_TM_TRP';
PROCEDURE_NAME := 'sap.tm.trp.db.pipeline::kpi_idle_rate';
TABLE_NAME := 'sap.tm.trp.db.pipeline::kpi_idle_rate.META';
PROCEDURE_DESC := 'Default KPI Calculation Model';
PIPELINE_NAME := 'DFT_KPI_CM';
PIPELINE_DESC := 'Default KPI Calculation Model';
PIPELINE_TYPE_ID := 2;
CALL "SAP_TM_TRP"."sap.tm.trp.db.pipeline::p_register_pipeline_model"(:SCHEMA_NAME,:PROCEDURE_NAME,:TABLE_NAME,:PROCEDURE_DESC,:PIPELINE_NAME,
																	  :PIPELINE_DESC,:PIPELINE_TYPE_ID,:ENTRY_ID,:KPI_PIPELINE_MODEL_ID);
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_register_controller_for_pipeline_model"(:KPI_PIPELINE_MODEL_ID);																	  
																	 
END;


------------------------create alert rule group---------------------
BEGIN

DECLARE ALERT_GROUP_NAME VARCHAR(50);
DECLARE ALERT_GROUP_DESC VARCHAR(200);
DECLARE ALERT_RULE_GROUP_CATEGORY_ID INTEGER;
DECLARE ALLOWED_USAGED_ID VARCHAR(10);
DECLARE SD_ALERT_RULE_GROUP_ID BIGINT;
DECLARE KPI_ALERT_RULE_GROUP_ID BIGINT;
DECLARE RULE_ID_LIST TABLE (RULE_ID BIGINT);
DECLARE RULE_ID_ARR BIGINT ARRAY;
DECLARE SUCCESS_FLAG INT;

--create Supply Demand Rule Group DFT_SD_AR_GRP
ALERT_GROUP_NAME := 'DFT_SD_AR_GRP';
ALERT_GROUP_DESC := 'Default Supply&Demand Alert Rule Group';
ALERT_RULE_GROUP_CATEGORY_ID := 1;
ALLOWED_USAGED_ID := 'G';

CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_create_ruleGroup" (:ALERT_GROUP_NAME,:ALERT_GROUP_DESC,:ALERT_RULE_GROUP_CATEGORY_ID,:ALLOWED_USAGED_ID,:SD_ALERT_RULE_GROUP_ID);
RULE_ID_ARR[1] := :SD_STOCK_ALERT_RULE_ID;
RULE_ID_ARR[2] := :SD_FCST_ALERT_RULE_ID;
RULE_ID_LIST = UNNEST(:RULE_ID_ARR) AS ("RULE_ID");
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_adjust_rule_group_items"(:SD_ALERT_RULE_GROUP_ID,:RULE_ID_LIST,:SUCCESS_FLAG);

--create Supply Demand Rule Group DFT_KPI_AR_GRP
ALERT_GROUP_NAME := 'DFT_KPI_AR_GRP';
ALERT_GROUP_DESC := 'Default KPI Alert Rule Group';
ALERT_RULE_GROUP_CATEGORY_ID := 2;
ALLOWED_USAGED_ID := 'G';

CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_create_ruleGroup" (:ALERT_GROUP_NAME,:ALERT_GROUP_DESC,:ALERT_RULE_GROUP_CATEGORY_ID,:ALLOWED_USAGED_ID,:KPI_ALERT_RULE_GROUP_ID);
RULE_ID_ARR := TRIM_ARRAY(:RULE_ID_ARR,2);
RULE_ID_ARR[1] := :IDLE_RATE_ALERT_RULE_ID;
RULE_ID_LIST = UNNEST(:RULE_ID_ARR) AS ("RULE_ID");
CALL "SAP_TM_TRP"."sap.tm.trp.db.hrf.ruleManage.ruleGroup::p_adjust_rule_group_items"(:KPI_ALERT_RULE_GROUP_ID,:RULE_ID_LIST,:SUCCESS_FLAG);


END;





-----------------------------------load leasing contract--------------------------------------
BEGIN

DECLARE MSG NVARCHAR(500);

DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src" VALUES('2','LESSOR_AGREMENT_REFERENCE','YML','ADDRESS_LINE1',NULL,NULL,'YML',NULL,NULL,'US',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.sap.com/index.html');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src" VALUES('3','LESSOR_AGREMENT_REFERENCE','COSCO','ADDRESS_LINE1',NULL,NULL,'COSCO',NULL,NULL,'US',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.sap.com/index.html');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lessor_ext_src" VALUES('1','LESSOR_AGREMENT_REFERENCE','MSK','ADDRESS_LINE1',NULL,NULL,'MSK',NULL,NULL,'CN',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.sap.com/index.html');
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src" VALUES('1','SHORT TERM');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src" VALUES('2','LONG TERM');
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_type_ext_src" VALUES('3','OneWay Lease');
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('2','1002','1','2',TO_TIMESTAMP('Aug 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Aug 11, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'EUR',NULL,TO_TIMESTAMP('Jul 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,NULL,1000,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('3','1004','2','2',TO_TIMESTAMP('Oct 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Oct 11, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'EUR',NULL,TO_TIMESTAMP('Oct 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,NULL,1000,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('4','1003','1','3',TO_TIMESTAMP('Aug 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Aug 11, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'EUR',NULL,TO_TIMESTAMP('Jul 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,NULL,1000,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('1','1001','1','1',TO_TIMESTAMP('May 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('May 11, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'USD',NULL,TO_TIMESTAMP('Apr 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,NULL,1000,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_ext_src" VALUES('5','1005','2','1',TO_TIMESTAMP('Jan 1, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Dec 31, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'EUR',NULL,TO_TIMESTAMP('Jul 11, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,TO_TIMESTAMP('Dec 22, 2014 9:09:01.058 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,30000,NULL,1);
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '4','5','10ST',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.94 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '5','5','10RF',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.942 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '6','5','10HC',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.944 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '7','5','10OT',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.945 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '8','5','20ST',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.946 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES( '9','5','20HC',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.948 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('10','5','30PL',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.949 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('11','5','20BH',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.95 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('12','5','20BK',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.951 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.951 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('13','5','40ST',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.953 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.953 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('14','5','30HC',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.954 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.954 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('15','5','20CH',NULL,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.955 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.955 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('16','5','20CO',NULL,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.956 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.956 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('17','5','20FB',NULL,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.958 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.958 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('18','5','20FF',NULL,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.959 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.959 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('19','5','20FR',NULL,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.96 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.96 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('20','5','20GA',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.961 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.961 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('21','5','20GO',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.962 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.962 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('22','5','20HO',NULL,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.964 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.964 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('23','5','20HR',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.965 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.965 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('24','5','20HW',1,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.966 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.966 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_per_diem_ext_src" VALUES('25','5','20IN',NULL,10,TO_TIMESTAMP('Jan 14, 2015 3:06:43.967 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 3:06:43.967 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES('19','5',TO_TIMESTAMP('Jan 1, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'FRBRU',1,1,'10HC',10,300,75,NULL,NULL,TO_TIMESTAMP('Dec 24, 2014 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Dec 24, 2014 3:00:16.77 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES('17','5',TO_TIMESTAMP('Jan 1, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2014 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'USSWW',1,1,'10ST',10,300,300,NULL,NULL,TO_TIMESTAMP('Dec 22, 2014 9:18:57.79 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Dec 22, 2014 9:18:57.79 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,1,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES('39','5',TO_TIMESTAMP('Jan 1, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'USSWW',1,1,'10ST',10,100,150,200,NULL,TO_TIMESTAMP('Jan 15, 2015 10:41:30.506 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jan 15, 2015 10:41:30.506 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,2,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_term_ext_src" VALUES('41','5',TO_TIMESTAMP('Jan 1, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jun 30, 2015 12:00:00.0 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),'FRBRU',1,1,'10HC',10,100,150,200,NULL,TO_TIMESTAMP('Jan 15, 2015 10:41:30.509 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jan 15, 2015 10:41:30.509 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,2,1);
DELETE FROM "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_condition_ext_src";
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_condition_ext_src" VALUES('17','5','USSWW',1,1,'10ST',10,100,1,TO_TIMESTAMP('Jan 14, 2015 2:56:17.135 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 2:56:17.135 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_condition_ext_src" VALUES('19','5','FRBRU',1,1,'10HC',10,100,1,TO_TIMESTAMP('Jan 14, 2015 2:56:17.139 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),TO_TIMESTAMP('Jan 14, 2015 2:56:17.139 PM','MON DD, YYYY HH24:MI:SS.FF3 PM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_condition_ext_src" VALUES('61','5','USSWW',1,1,'10ST',15,150,2,TO_TIMESTAMP('Jan 15, 2015 10:46:15.706 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jan 15, 2015 10:46:15.706 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,1);
INSERT INTO "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::t_lease_contract_hire_condition_ext_src" VALUES('63','5','FRBRU',1,1,'10HC',15,150,2,TO_TIMESTAMP('Jan 15, 2015 10:46:15.708 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),TO_TIMESTAMP('Jan 15, 2015 10:46:15.708 AM','MON DD, YYYY HH24:MI:SS.FF3 AM'),NULL,NULL,1);
CALL "SAP_TM_TRP"."sap.tm.trp.db.dataprovisioning::sp_lease_contract_data_provision"(:MSG);

END;

END;
