DROP PROCEDURE "SYSTEM"."Z_MIGRATE_FROM_TEMP_TO_TRP";
CREATE PROCEDURE "SYSTEM"."Z_MIGRATE_FROM_TEMP_TO_TRP"()
AS

BEGIN
DECLARE TAB_ARR NVARCHAR(256) ARRAY;
DECLARE COLS_ARR NVARCHAR(1000) ARRAY;
DECLARE ARR_INDEX INT;
DECLARE SOURCE_SCHEMA NVARCHAR(256);
DECLARE TARGET_SCHEMA NVARCHAR(256);
DECLARE TABLE_NAME NVARCHAR(256);
DECLARE SQLSTR NVARCHAR(5000);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
SELECT :SQLSTR, ::SQL_ERROR_CODE, ::SQL_ERROR_MESSAGE FROM DUMMY;
ROLLBACK;
END;

BEGIN
TARGET_SCHEMA := '"SAP_TM_TRP"';
SOURCE_SCHEMA := 'SAP_TM_TRP_TMP';
TAB_LIST = SELECT TABLE_NAME,STRING_AGG(COLUMN_NAME,'","') AS COLUMNS_STRING FROM TABLE_COLUMNS WHERE SCHEMA_NAME = :SOURCE_SCHEMA GROUP BY TABLE_NAME ORDER BY TABLE_NAME;
TAB_ARR := ARRAY_AGG(:TAB_LIST.TABLE_NAME);
FOR ARR_INDEX IN 1 .. CARDINALITY(:TAB_ARR) DO
SQLSTR := 'DELETE FROM' || ' ' || :TARGET_SCHEMA || '.' || '"' || :TAB_ARR[:ARR_INDEX] || '"';
EXECUTE IMMEDIATE :SQLSTR;
END FOR;
COMMIT;
END;

BEGIN
SOURCE_SCHEMA := 'SAP_TM_TRP_TMP';
TARGET_SCHEMA := '"SAP_TM_TRP"';

TAB_LIST = SELECT TABLE_NAME,STRING_AGG(COLUMN_NAME,'","') AS COLUMNS_STRING FROM TABLE_COLUMNS WHERE SCHEMA_NAME = :SOURCE_SCHEMA GROUP BY TABLE_NAME ORDER BY TABLE_NAME;
TAB_ARR := ARRAY_AGG(:TAB_LIST.TABLE_NAME);
COLS_ARR := ARRAY_AGG(:TAB_LIST.COLUMNS_STRING);
FOR ARR_INDEX IN 1 .. CARDINALITY(:TAB_ARR) DO
SQLSTR := 'INSERT INTO' || ' ' || :TARGET_SCHEMA || '.' || '"' || :TAB_ARR[:ARR_INDEX] || '"' || ' ' 
|| '("' || :COLS_ARR[:ARR_INDEX] || '")' || ' ' 
|| 'SELECT' || ' ' || '"' || :COLS_ARR[:ARR_INDEX] || '"' || ' ' ||
 'FROM' || ' ' || :SOURCE_SCHEMA || '.' || '"' || :TAB_ARR[:ARR_INDEX] || '"';
EXECUTE IMMEDIATE :SQLSTR;
END FOR;


END;

END;

CALL "SYSTEM"."Z_MIGRATE_FROM_TEMP_TO_TRP"();