CREATE SCHEMA SAPTM;
GRANT SELECT ON SCHEMA SAPTM TO _SYS_REPO WITH GRANT OPTION;
CREATE SYNONYM "SAPTM"."/SAPAPO/LOC" FOR "SAP<SID>"."/SAPAPO/LOC";
CREATE SYNONYM "SAPTM"."/SAPAPO/LOCT" FOR "SAP<SID>"."/SAPAPO/LOCT";
CREATE SYNONYM "SAPTM"."/SAPAPO/RELDSTR" FOR "SAP<SID>"."/SAPAPO/RELDSTR";
CREATE SYNONYM "SAPTM"."/SAPAPO/RELDSTRT" FOR "SAP<SID>"."/SAPAPO/RELDSTRT";
CREATE SYNONYM "SAPTM"."/SAPAPO/RELEHZON" FOR "SAP<SID>"."/SAPAPO/RELEHZON";
CREATE SYNONYM "SAPTM"."/SAPAPO/RES_HEAD" FOR "SAP<SID>"."/SAPAPO/RES_HEAD";
CREATE SYNONYM "SAPTM"."/SAPAPO/T005S" FOR "SAP<SID>"."/SAPAPO/T005S";
CREATE SYNONYM "SAPTM"."/SCMB/EQUI_CODE" FOR "SAP<SID>"."/SCMB/EQUI_CODE";
CREATE SYNONYM "SAPTM"."/SCMB/EQUI_CODET" FOR "SAP<SID>"."/SCMB/EQUI_CODET";
CREATE SYNONYM "SAPTM"."/SCMB/RESTMSHD" FOR "SAP<SID>"."/SCMB/RESTMSHD";
CREATE SYNONYM "SAPTM"."/SCMB/TOENTITY" FOR "SAP<SID>"."/SCMB/TOENTITY";
CREATE SYNONYM "SAPTM"."/SCMB/TOENTITYT" FOR "SAP<SID>"."/SCMB/TOENTITYT";
CREATE SYNONYM "SAPTM"."/SCMB/ZONE" FOR "SAP<SID>"."/SCMB/ZONE";
CREATE SYNONYM "SAPTM"."/SCMB/ZONET" FOR "SAP<SID>"."/SCMB/ZONET";
CREATE SYNONYM "SAPTM"."/SCMB/ZONE_D" FOR "SAP<SID>"."/SCMB/ZONE_D";
CREATE SYNONYM "SAPTM"."/SCMB/ZONE_P" FOR "SAP<SID>"."/SCMB/ZONE_P";
CREATE SYNONYM "SAPTM"."/SCMB/ZONE_R" FOR "SAP<SID>"."/SCMB/ZONE_R";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_SHLOC" FOR "SAP<SID>"."/SCMTMS/D_SHLOC";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_SHZON" FOR "SAP<SID>"."/SCMTMS/D_SHZON";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TOREXE" FOR "SAP<SID>"."/SCMTMS/D_TOREXE";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TORITE" FOR "SAP<SID>"."/SCMTMS/D_TORITE";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TORROT" FOR "SAP<SID>"."/SCMTMS/D_TORROT";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TORSTP" FOR "SAP<SID>"."/SCMTMS/D_TORSTP";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TORSTS" FOR "SAP<SID>"."/SCMTMS/D_TORSTS";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TRQITM" FOR "SAP<SID>"."/SCMTMS/D_TRQITM";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TRQROT" FOR "SAP<SID>"."/SCMTMS/D_TRQROT";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TRQSTG" FOR "SAP<SID>"."/SCMTMS/D_TRQSTG";
CREATE SYNONYM "SAPTM"."/SCMTMS/RES_POS" FOR "SAP<SID>"."/SCMTMS/RES_POS";
CREATE SYNONYM "SAPTM"."ADRC" FOR "SAP<SID>"."ADRC";
CREATE SYNONYM "SAPTM"."ADRCITY" FOR "SAP<SID>"."ADRCITY";
CREATE SYNONYM "SAPTM"."ADRCITYPRT" FOR "SAP<SID>"."ADRCITYPRT";
CREATE SYNONYM "SAPTM"."ADRCITYT" FOR "SAP<SID>"."ADRCITYT";
CREATE SYNONYM "SAPTM"."ADRCT" FOR "SAP<SID>"."ADRCT";
CREATE SYNONYM "SAPTM"."ADRP" FOR "SAP<SID>"."ADRP";
CREATE SYNONYM "SAPTM"."ADRPCDCITY" FOR "SAP<SID>"."ADRPCDCITY";
CREATE SYNONYM "SAPTM"."ADRPSTCODE" FOR "SAP<SID>"."ADRPSTCODE";
CREATE SYNONYM "SAPTM"."BUT000" FOR "SAP<SID>"."BUT000";
CREATE SYNONYM "SAPTM"."DD07L" FOR "SAP<SID>"."DD07L";
CREATE SYNONYM "SAPTM"."DD07T" FOR "SAP<SID>"."DD07T";
CREATE SYNONYM "SAPTM"."T002" FOR "SAP<SID>"."T002";
CREATE SYNONYM "SAPTM"."T002T" FOR "SAP<SID>"."T002T";
CREATE SYNONYM "SAPTM"."T005" FOR "SAP<SID>"."T005";
CREATE SYNONYM "SAPTM"."T005B" FOR "SAP<SID>"."T005B";
CREATE SYNONYM "SAPTM"."T005E" FOR "SAP<SID>"."T005E";
CREATE SYNONYM "SAPTM"."T005F" FOR "SAP<SID>"."T005F";
CREATE SYNONYM "SAPTM"."T005G" FOR "SAP<SID>"."T005G";
CREATE SYNONYM "SAPTM"."T005H" FOR "SAP<SID>"."T005H";
CREATE SYNONYM "SAPTM"."T005S" FOR "SAP<SID>"."T005S";
CREATE SYNONYM "SAPTM"."T005T" FOR "SAP<SID>"."T005T";
CREATE SYNONYM "SAPTM"."T005U" FOR "SAP<SID>"."T005U";
CREATE SYNONYM "SAPTM"."T005X" FOR "SAP<SID>"."T005X";
CREATE SYNONYM "SAPTM"."T005ZT" FOR "SAP<SID>"."T005ZT";
CREATE SYNONYM "SAPTM"."T006" FOR "SAP<SID>"."T006";
CREATE SYNONYM "SAPTM"."T006A" FOR "SAP<SID>"."T006A";
CREATE SYNONYM "SAPTM"."T006D" FOR "SAP<SID>"."T006D";
CREATE SYNONYM "SAPTM"."T006T" FOR "SAP<SID>"."T006T";
CREATE SYNONYM "SAPTM"."TTZD" FOR "SAP<SID>"."TTZD";
CREATE SYNONYM "SAPTM"."TTZDF" FOR "SAP<SID>"."TTZDF";
CREATE SYNONYM "SAPTM"."TTZDV" FOR "SAP<SID>"."TTZDV";
CREATE SYNONYM "SAPTM"."TTZR" FOR "SAP<SID>"."TTZR";
CREATE SYNONYM "SAPTM"."TTZZ" FOR "SAP<SID>"."TTZZ";
CREATE SYNONYM "SAPTM"."TTZZT" FOR "SAP<SID>"."TTZZT";
CREATE SYNONYM "SAPTM"."USR01" FOR "SAP<SID>"."USR01";
CREATE SYNONYM "SAPTM"."USR02" FOR "SAP<SID>"."USR02";
CREATE SYNONYM "SAPTM"."USR21" FOR "SAP<SID>"."USR21";
CREATE SYNONYM "SAPTM"."USRACL" FOR "SAP<SID>"."USRACL";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_SCHDEP" FOR "SAP<SID>"."/SCMTMS/D_SCHDEP";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_SCHDPL" FOR "SAP<SID>"."/SCMTMS/D_SCHDPL";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_SCHLOC" FOR "SAP<SID>"."/SCMTMS/D_SCHLOC";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_SCHROT" FOR "SAP<SID>"."/SCMTMS/D_SCHROT";
CREATE SYNONYM "SAPTM"."/SAPAPO/RESDOWN" FOR "SAP<SID>"."/SAPAPO/RESDOWN";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_TORCC" FOR "SAP<SID>"."/SCMTMS/D_TORCC";
CREATE SYNONYM "SAPTM"."USRSTAMP" FOR "SAP<SID>"."USRSTAMP";
CREATE SYNONYM "SAPTM"."/SCMB/HRP5561" FOR "SAP<SID>"."/SCMB/HRP5561";
CREATE SYNONYM "SAPTM"."BUT100" FOR "SAP<SID>"."BUT100";
CREATE SYNONYM "SAPTM"."/SCMTMS/D_FAGROT" FOR "SAP<SID>"."/SCMTMS/D_FAGROT";
CREATE SYNONYM "SAPTM"."/SCMTMS/C_FATYPE" FOR "SAP<SID>"."/SCMTMS/C_FATYPE";
CREATE SYNONYM "SAPTM"."/SAPAPO/TMODCOD" FOR "SAP<SID>"."/SAPAPO/TMODCOD";
CREATE SYNONYM "SAPTM"."/SAPAPO/TMODCODT" FOR "SAP<SID>"."/SAPAPO/TMODCODT";
CREATE SYNONYM "SAPTM"."/TRP/RES_SHTRK" FOR "SAP<SID>"."/TRP/RES_SHTRK";
CREATE SYNONYM "SAPTM"."/TRP/RES_TRKLOG" FOR "SAP<SID>"."/TRP/RES_TRKLOG";
CREATE SYNONYM "SAPTM"."/TRP/RES_TRKMAP" FOR "SAP<SID>"."/TRP/RES_TRKMAP";
CREATE SYNONYM "SAPTM"."/TRP/RES_TPACT" FOR "SAP<SID>"."/TRP/RES_TPACT";
CREATE SYNONYM "SAPTM"."/TRP/RES_TPACTT" FOR "SAP<SID>"."/TRP/RES_TPACTT";
CREATE SYNONYM "SAPTM"."/TRP/RES_OWNSHP" FOR "SAP<SID>"."/TRP/RES_OWNSHP";
CREATE SYNONYM "SAPTM"."/TRP/RES_OWNSHPT" FOR "SAP<SID>"."/TRP/RES_OWNSHPT";
CREATE SYNONYM "SAPTM"."/TRP/RES_STATUS" FOR "SAP<SID>"."/TRP/RES_STATUS";
CREATE SYNONYM "SAPTM"."/TRP/RES_STATUST" FOR "SAP<SID>"."/TRP/RES_STATUST";
CREATE SYNONYM "SAPTM"."/SAPAPO/LOC_EQUI" FOR "SAP<SID>"."/SAPAPO/LOC_EQUI";
CREATE SYNONYM "SAPTM"."/SCMB/C_RESCLS" FOR "SAP<SID>"."/SCMB/C_RESCLS";
CREATE SYNONYM "SAPTM"."DD03L" FOR "SAP<SID>"."DD03L";
CREATE SYNONYM "SAPTM"."DD01L" FOR "SAP<SID>"."DD01L";
CREATE SYNONYM "SAPTM"."DD04T" FOR "SAP<SID>"."DD04T";
CREATE SYNONYM "SAPTM"."DD04L" FOR "SAP<SID>"."DD04L";
CREATE SYNONYM "SAPTM"."AGR_USERS" FOR "SAP<SID>"."AGR_USERS";


CREATE SCHEMA SAP_TM_TRP; 
GRANT CREATE ANY, SELECT, ALTER, CREATE ANY, EXECUTE, DELETE, UPDATE, INSERT, DROP, INDEX, DEBUG, TRIGGER, REFERENCES ON SCHEMA SAP_TM_TRP TO _SYS_REPO WITH GRANT OPTION;


CREATE COLUMN TABLE "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement::t_in_polygon" ("GEOMETRY" ST_GEOMETRY(0) CS_GEOMETRY,"UUID" VARCHAR(32)) UNLOAD PRIORITY 5 AUTO MERGE;
GRANT SELECT, DELETE, UPDATE, INSERT ON "SAP_TM_TRP"."sap.tm.trp.db.systemmanagement::t_in_polygon" TO _SYS_REPO WITH GRANT OPTION;

CREATE VIEW "SAP_TM_TRP"."sap.tm.trp.db.booking::v_booking_extended_generated" ( "KEY",
	 "C1",
	 "C2",
	 "C3",
	 "C4",
	 "C5" ) AS SELECT
	 null AS "KEY" ,
	 null AS C1,
	 null AS C2,
	 null AS C3,
	 null AS C4,
	 null AS C5 
FROM dummy WITH READ ONLY;
GRANT SELECT ON "SAP_TM_TRP"."sap.tm.trp.db.booking::v_booking_extended_generated" TO _SYS_REPO WITH GRANT OPTION;

CREATE VIEW "SAP_TM_TRP"."sap.tm.trp.db.booking::v_booking_hrf" ( 
     "TU_ID",
	 "ITE_KEY"
 ) AS SELECT
	 null as "TU_ID" ,
	 null "ITE_KEY" 
FROM dummy WITH READ ONLY;

GRANT SELECT ON "SAP_TM_TRP"."sap.tm.trp.db.booking::v_booking_hrf" TO _SYS_REPO WITH GRANT OPTION;