CREATE PROCEDURE "SAP_TM_TRP"."P_FIND_PROPER_FO"(IN ZONE_NAME NVARCHAR(20)) AS
BEGIN

DECLARE ZONE_ID NVARCHAR(22);

SELECT SCUGUID22 INTO ZONE_ID FROM "SAPTMW"."/SCMB/TOENTITY" WHERE ENTITY = :ZONE_NAME AND MANDT = '800';
ZONEID_LV1 = SELECT DISTINCT A.CNODEID AS ZONEID,B.ENTITY AS ZONE_NAME FROM "SAPTMW"."Z_ZONE_HRC" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.CNODEID = B.SCUGUID22
WHERE A.PNODEID = :ZONE_ID AND B.MANDT = '800';
LOC_LV1 = SELECT A.LOCNO AS LOCNO,B.SCUGUID22 AS ID FROM "SAPTMW"."Z_ZONE_D" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.LOCNO = B.ENTITY
WHERE A.ID_ZONE IN (SELECT DISTINCT ZONE_NAME FROM :ZONEID_LV1) AND A.LOCNO IN (SELECT LOCNO FROM "SAPTMW"."Z_BKLOC")
AND B.MANDT = '800';


ZONEID_LV2 = SELECT DISTINCT A.CNODEID AS ZONEID,B.ENTITY AS ZONE_NAME FROM "SAPTMW"."Z_ZONE_HRC" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.CNODEID = B.SCUGUID22
WHERE A.PNODEID IN (SELECT DISTINCT ZONEID FROM :ZONEID_LV1) AND B.MANDT = '800';
LOC_LV2 = SELECT A.LOCNO AS LOCNO,B.SCUGUID22 AS ID FROM "SAPTMW"."Z_ZONE_D" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.LOCNO = B.ENTITY
WHERE A.ID_ZONE IN (SELECT DISTINCT ZONE_NAME FROM :ZONEID_LV2) AND A.LOCNO IN (SELECT LOCNO FROM "SAPTMW"."Z_BKLOC")
AND B.MANDT = '800';



ZONEID_LV3 = SELECT DISTINCT A.CNODEID AS ZONEID,B.ENTITY AS ZONE_NAME FROM "SAPTMW"."Z_ZONE_HRC" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.CNODEID = B.SCUGUID22
WHERE A.PNODEID IN (SELECT DISTINCT ZONEID FROM :ZONEID_LV2) AND B.MANDT = '800';
LOC_LV3 = SELECT A.LOCNO AS LOCNO,B.SCUGUID22 AS ID FROM "SAPTMW"."Z_ZONE_D" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.LOCNO = B.ENTITY
WHERE A.ID_ZONE IN (SELECT DISTINCT ZONE_NAME FROM :ZONEID_LV3) AND A.LOCNO IN (SELECT LOCNO FROM "SAPTMW"."Z_BKLOC")
AND B.MANDT = '800';

ZONEID_LV4 = SELECT DISTINCT A.CNODEID AS ZONEID,B.ENTITY AS ZONE_NAME FROM "SAPTMW"."Z_ZONE_HRC" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.CNODEID = B.SCUGUID22
WHERE A.PNODEID IN (SELECT DISTINCT ZONEID FROM :ZONEID_LV3) AND B.MANDT = '800';
LOC_LV4 = SELECT A.LOCNO AS LOCNO,B.SCUGUID22 AS ID FROM "SAPTMW"."Z_ZONE_D" AS A INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B ON A.LOCNO = B.ENTITY
WHERE A.ID_ZONE IN (SELECT DISTINCT ZONE_NAME FROM :ZONEID_LV4) AND A.LOCNO IN (SELECT LOCNO FROM "SAPTMW"."Z_BKLOC")
AND B.MANDT = '800';


LOC_TAB =
SELECT DISTINCT LOCNO FROM (
SELECT LOCNO FROM :LOC_LV1
UNION
SELECT LOCNO FROM :LOC_LV2
UNION
SELECT LOCNO FROM :LOC_LV3
UNION
SELECT LOCNO FROM :LOC_LV4
);


SELECT DISTINCT F.TRQ_ID AS TRQ,M.TOR_ID AS TOR,A.SRC_LOC_ID AS POL,A.DES_LOC_ID AS POD,I.SCH_ID AS SCHEDULE_ID,G.VOYAGE AS VOYAGE FROM
"SAPTMW"."/SCMTMS/D_TRQSTG" AS A
INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS B
ON A.SRC_LOC_ID = B.ENTITY AND A.MANDT = B.MANDT
INNER JOIN "SAPTMW"."/SCMB/TOENTITY" AS C
ON A.DES_LOC_ID = C.ENTITY AND A.MANDT = B.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_SCHDPL" AS D
ON B.SCUGUID = D.LOC_UUID AND B.MANDT = D.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_SCHDPL" AS E
ON D.PARENT_KEY = E.PARENT_KEY
AND C.SCUGUID = E.LOC_UUID
AND D.MANDT = E.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_TRQROT" AS F
ON F.DB_KEY = A.PARENT_KEY AND A.MANDT = F.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_SCHDEP" AS G
ON E.PARENT_KEY = G.DB_KEY
AND E.MANDT = G.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_SCHROT" AS I
ON G.PARENT_KEY = I.DB_KEY AND G.MANDT = I.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_TORITE" AS K
ON F.DB_KEY = K.REF_TRQ_ROOT_KEY AND A.MANDT = K.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_TORROT" AS M
ON K.PARENT_KEY = M.DB_KEY AND K.MANDT = M.MANDT
INNER JOIN "SAPTMW"."/SCMTMS/D_TORSTS" AS O
ON O.ROOT_KEY = M.DB_KEY AND O.MANDT = M.MANDT
WHERE A.MANDT = '800'
AND A.SRC_LOC_ID IN (SELECT LOCNO FROM :LOC_TAB)
AND A.DES_LOC_ID IN (SELECT LOCNO FROM :LOC_TAB)
AND F.CREATED_BY = 'I075181'
AND A.STAGE_TYPE = '03'
AND SUBSTRING(TO_VARCHAR(A.PIC_EAR_REQ),1,8) = SUBSTRING(TO_VARCHAR(D.DEPARTURE_UTC),1,8)
AND O.SUCCESSOR_ID = '0000000020'
ORDER BY TRQ, TOR_ID, SCHEDULE_ID, VOYAGE;


END;