PROCEDURE "SAP_TM_TRP"."sap.tm.trp.config::reset_passwd" (IN USER_NAME NVARCHAR(50),IN TARGET_PASS NVARCHAR(50))
    LANGUAGE SQLSCRIPT
    SQL SECURITY INVOKER 
    DEFAULT SCHEMA "SAP_TM_TRP"
    AS
    LAST_USED_TIMES INT;
    RANDOM_STR VARCHAR(32);
    ALTER_SQL VARCHAR(200);
BEGIN

    SELECT VALUE INTO LAST_USED_TIMES FROM M_PASSWORD_POLICY WHERE PROPERTY = 'last_used_passwords';
    WHILE :LAST_USED_TIMES >= 0 DO
        SELECT TO_VARCHAR(SYSUUID) INTO RANDOM_STR FROM DUMMY;    
        ALTER_SQL := 'ALTER USER ' || :USER_NAME || ' PASSWORD ' || 'Qwer_1' || :RANDOM_STR;
        EXECUTE IMMEDIATE :ALTER_SQL;
        EXECUTE IMMEDIATE 'COMMIT';
        LAST_USED_TIMES := :LAST_USED_TIMES - 1;
    END WHILE;
    SELECT TO_VARCHAR(SYSUUID) INTO RANDOM_STR FROM DUMMY; 
    ALTER_SQL := 'ALTER USER ' || :USER_NAME || ' PASSWORD ' || :TARGET_PASS;
    EXECUTE IMMEDIATE :ALTER_SQL;
    EXECUTE IMMEDIATE 'COMMIT';
    ALTER_SQL := 'ALTER USER ' || :USER_NAME || ' RESET CONNECT ATTEMPTS';
    EXECUTE IMMEDIATE :ALTER_SQL;
    EXECUTE IMMEDIATE 'COMMIT';    

END;