--fetch all persistent tables
SELECT TABLE_NAME FROM TABLES WHERE SCHEMA_NAME = 'SAP_TM_TRP' AND IS_TEMPORARY = 'FALSE' AND TABLE_NAME IN (
SELECT DISTINCT CONCAT(CONCAT(PACKAGE_ID,'::'),OBJECT_NAME) AS TABLE_NAME FROM "_SYS_REPO"."ACTIVE_OBJECT"
 WHERE PACKAGE_ID LIKE 'sap.tm.trp.db%' AND OBJECT_SUFFIX = 'hdbtable' ) ORDER BY TABLE_NAME;
 
--fetch all table columns
SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE_NAME,LENGTH,IS_NULLABLE FROM TABLE_COLUMNS 
WHERE SCHEMA_NAME = 'SAP_TM_TRP' AND TABLE_NAME IN 
(SELECT TABLE_NAME FROM TABLES WHERE SCHEMA_NAME = 'SAP_TM_TRP' AND IS_TEMPORARY = 'FALSE' AND TABLE_NAME IN (
SELECT DISTINCT CONCAT(CONCAT(PACKAGE_ID,'::'),OBJECT_NAME) AS TABLE_NAME FROM "_SYS_REPO"."ACTIVE_OBJECT"
 WHERE PACKAGE_ID LIKE 'sap.tm.trp.db%' AND OBJECT_SUFFIX = 'hdbtable' ) ORDER BY TABLE_NAME) 
 ORDER BY TABLE_NAME, COLUMN_NAME;
 
 
 --fetch all indexes
 SELECT TABLE_NAME,COLUMN_NAME,CONSTRAINT FROM INDEX_COLUMNS WHERE SCHEMA_NAME = 'SAP_TM_TRP' AND TABLE_NAME IN
( SELECT TABLE_NAME FROM TABLES WHERE SCHEMA_NAME = 'SAP_TM_TRP' AND IS_TEMPORARY = 'FALSE' AND TABLE_NAME IN (
SELECT DISTINCT CONCAT(CONCAT(PACKAGE_ID,'::'),OBJECT_NAME) AS TABLE_NAME FROM "_SYS_REPO"."ACTIVE_OBJECT"
 WHERE PACKAGE_ID LIKE 'sap.tm.trp.db%' AND OBJECT_SUFFIX = 'hdbtable' ) ORDER BY TABLE_NAME )
 ORDER BY TABLE_NAME,COLUMN_NAME;